// AdoptionRepository — thin Drizzle wrapper for adoption domain writes and reads.
// Accepts an optional `tx` parameter for use inside db.transaction() calls,
// mirroring the existing openCase(input, tx) pattern in the codebase.
// Returns domain types or lightweight shapes (not raw Drizzle row types).
// No auth logic — auth lives at the action / use-case edge.

import { and, desc, eq, inArray, isNull, ne, sql } from "drizzle-orm";

import { db, organizations, ownerships, petEvents, pets } from "@/db";
import { insertEventIdempotent } from "@/lib/events/event-idempotency";
import { validateEventPayload } from "@/lib/events/event-schemas";
import {
  findOpenAdoptionApplicationCase,
  findOpenAdoptionListingCase,
  findOpenCaseForPetAndKind,
  openCase,
} from "@/lib/infra/case-helpers";
import { ORG_CUSTODY_TAKEN_ERROR, findLiveOrgShelterCustody } from "@/lib/infra/org-custody";
import { unerasedPetByToken } from "@/lib/infra/public-pet-lookup";

import { ADOPTER_NO_LONGER_HOLDS_ERROR, ReversalRefused } from "../domain/reversal-rules";
import { consultAdopterAccountByDni } from "./adopter-dni-consult";
import {
  type InsertAdoptionFinalizedArgs,
  insertAdoptionFinalized,
} from "./adoption-finalize-writer";
import { AdoptionPublicReads } from "./adoption-public-reads";
import {
  applicationCloseNote,
  closeApplicationCase,
  findOpenCaseForApplication,
} from "./application-case-close";

export type { InsertAdoptionFinalizedArgs };

// ---------------------------------------------------------------------------
// Type aliases
// ---------------------------------------------------------------------------

type Tx = Parameters<Parameters<typeof db.transaction>[0]>[0];
type PetRow = typeof pets.$inferSelect;
type FosterRow = { id: string; ownerUserId: string | null };
type SetEligibilityArgs = {
  petId: string;
  eligible: boolean;
  ineligibleReason: string | null;
  ineligibleReasonNotes: string | null;
  ineligibleUntil: Date | null;
  now: Date;
  userId: string;
  orgId: string;
  orgVerified: boolean;
  /** Previous eligibility state captured by the use-case BEFORE writing. */
  previousState: { eligible: boolean | null; reason: string | null } | null;
};

type SetListingStatusArgs = {
  petId: string;
  action: "publish" | "pause" | "unpause" | "unpublish";
  currentListedAt: Date | null;
  now: Date;
};

type SetBulkEligibilityIdempotentArgs = {
  petId: string;
  eligible: boolean;
  ineligibleReason: string | null;
  ineligibleReasonNotes: string | null;
  ineligibleUntil: Date | null;
  now: Date;
  userId: string;
  orgId: string;
  orgVerified: boolean;
  /** Deterministic UUID derived from (bulkActionId + ":" + petId). */
  clientIdempotencyKey: string;
};

type BatchShelterPetForEligibility = {
  petId: string;
  publicToken: string;
};

type BatchShelterPetForListing = {
  petId: string;
  publicToken: string;
  adoptionListedAt: Date | null;
  status: string;
  adoptionEligible: boolean | null;
  inCustodyDispute: boolean | null;
  rabiesObservationStatus: string | null;
};

type UpdateListingContentArgs = {
  petId: string;
  story?: string | null;
  requirements?: string | null;
  ageBucket?: string | null;
  sizeEstimate?: string | null;
  energyLevel?: string | null;
  goodWithKids?: boolean | null;
  goodWithDogs?: boolean | null;
  goodWithCats?: boolean | null;
  needsYard?: boolean | null;
  feeArs?: number | null;
};

type InsertApplicationArgs = {
  petId: string;
  userId: string;
  orgId: string;
  housingType: string;
  otherPets: string | null;
  dailyRoutine: string | null;
  notes: string | null;
  motivation: string | null;
  priorPets: string | null;
  now: Date;
};

/** Derived from the column, so a widened `author_role` enum cannot drift from this. */
type AuthorRole = NonNullable<(typeof petEvents.$inferInsert)["authorRole"]>;

type ResolveApplicationArgs = {
  petId: string;
  applicationEventId: string;
  outcome: "approved" | "rejected" | "withdrawn";
  // For approved/rejected this is the shelter reviewer; for withdrawn it is the
  // applicant's own user id (they are the actor who resolved their application).
  reviewerUserId: string;
  orgId: string;
  orgVerified: boolean;
  reason?: string;
  autoGenerated?: boolean;
  notes: string | null;
  now: Date;
  /**
   * WHO IS SIGNING. Defaults to the shelter shape every org-side caller has
   * always written (`shelter`, `orgId`, `orgVerified`). When given it is the
   * COMPLETE signature and its `organizationId` is what gets stamped — `orgId`
   * above names the listing's org for the callers that omit `author`, it is
   * not a fallback for `author.organizationId`. The titular's withdraw cascade
   * (rehome-by-titular) passes `owner` with NO org on purpose: the person whose
   * act closed the listing is the author of its consequences — db/schema.ts,
   * "the test is who the author IS". The death cascade passes the SPONSORING
   * org explicitly (lib/infra/rehome-death-cascade.ts, "whose org").
   */
  author?: { role: AuthorRole; organizationId: string | null; verified: boolean };
  /**
   * Whether a `rejected` resolution CLOSES the application's case in the same
   * transaction (default: yes — see application-case-close.ts for when each
   * outcome closes). `false` is for the two callers that close the case
   * themselves, right after, with a note of their own that the applicant
   * reads (the titular's withdraw cascade and the death cascade):
   * `case_events` is append-only, and two `case_closed` entries for one close
   * would be a lie on the expediente. Ignored for `approved`, which never
   * closes here.
   */
  closeCase?: boolean;
};

type ShelterPetResult = (PetRow & { custodyOwnershipId: string }) | null;

// ---------------------------------------------------------------------------
// Reversal types
// ---------------------------------------------------------------------------

/**
 * Result of the reversibility gate. `ok: false` covers all three rejection
 * reasons the reverse-adoption use-case must enforce: no finalize event
 * authored by this org, already reversed (idempotency guard), or custody has
 * since moved off the adopter this finalize event names (stale finalize —
 * also the second line of defense against a double-reverse, since after the
 * first reversal the active ownership role is shelter_custody, not owner).
 */
type ReversibleAdoptionResult =
  | {
      ok: true;
      finalizeEventId: string;
      adopterOwnershipId: string;
      adopterUserId: string | null;
      petName: string;
    }
  | { ok: false; error: string };

type InsertAdoptionReversedArgs = {
  petId: string;
  userId: string;
  orgId: string;
  orgVerified: boolean;
  /** The active `owner` ownership row (the adopter) to close. */
  adopterOwnershipId: string;
  /** The `adoption_finalized` event this reversal retracts (event linkage). */
  finalizeEventId: string;
  reason: string | null;
  now: Date;
};

type OrgRow = typeof organizations.$inferSelect;

type PetWithOrgResult = {
  pet: PetRow & { custodyOwnershipId: string };
  org: OrgRow;
} | null;

// NOTE: ApplicationEventRow is intentionally NOT exported from the repository
// public surface. Callers receive only the projected shape defined per method.
// Keeping the raw row type internal prevents accidental PII leaks (the payload
// carries applicant name/phone/address/DNI) across module boundaries.
type ApplicationEventRow = typeof petEvents.$inferSelect;

/**
 * Projected application shape returned by findApplicationForReview.
 * Contains only the fields the review/info-request callers need.
 * The full event (including PII payload) stays in the immutable event log.
 */
type ApplicationReviewShape = {
  id: string;
  /** Extracted from payload — the only PII field callers legitimately need. */
  applicantUserId: string | null;
};

// ---------------------------------------------------------------------------
// Repository
// ---------------------------------------------------------------------------

/**
 * The fixed `text` of a kind=adoption_info_requested note (T3-A2b). The
 * shelter's own message goes in `info_request_message`; this label is what a
 * generic note reader shows, and it names nobody.
 */
export const INFO_REQUEST_NOTE_LABEL = "El refugio pidió más información sobre una postulación";

export const AdoptionRepository = {
  // THE CITIZEN-FACING READS, spread in from `adoption-public-reads.ts`.
  //
  // The split is a fact about where the code lives and not about how it is
  // called: every method below used to sit in this object literal, every one is
  // still reachable as `AdoptionRepository.findPetForPublicDetail(…)`, and
  // `typeof AdoptionRepository` still names all of them. What the other file
  // buys is that "what can a stranger read about an animal in adoption" is one
  // screen of code with `unerasedPetByToken` visible in it, rather than five
  // methods scattered through the org-side writes below.
  //
  // IT IS FIRST IN THE LITERAL ON PURPOSE. A later key with the same name would
  // silently WIN over a spread one, so a re-added `findPetForPublicDetail` down
  // this file would shadow the fenced version and no test in that other file
  // would notice. `adoption-public-reads.test.ts` asserts the identity of each
  // one against the module it came from, which is what makes that shadowing
  // fail loudly instead of quietly.
  ...AdoptionPublicReads,

  /**
   * Finds a pet by public token that is currently under active shelter_custody
   * by the given organization. Returns the pet row + custodyOwnershipId, or null.
   */
  async findShelterPet(
    petPublicToken: string,
    organizationId: string,
    tx?: Tx,
  ): Promise<ShelterPetResult> {
    const client = tx ?? db;
    const [row] = await client
      .select({ pet: pets, custodyOwnershipId: ownerships.id })
      .from(pets)
      .innerJoin(ownerships, eq(ownerships.petId, pets.id))
      .where(
        and(
          // Art. 16: an erased pet answers like a token that never existed.
          unerasedPetByToken(petPublicToken),
          eq(ownerships.ownerOrganizationId, organizationId),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
        ),
      )
      .limit(1);

    if (!row) return null;
    return { ...row.pet, custodyOwnershipId: row.custodyOwnershipId };
  },

  /**
   * The custody row finalize is about to close, re-read LIVE and FOR UPDATE
   * inside the finalize transaction (rehome-by-titular, WU5 carry-forward 3).
   *
   * `findShelterPet` runs before the transaction and is the readable refusal;
   * this is the guard. A titular's withdraw (`endCustodyRow`) committing
   * between the two used to let finalize complete an adoption over a custody
   * row that was already closed — or write `rehome_sponsorship_ended{adopted}`
   * beside a `withdrawn_by_titular` for the same row. Under the lock the
   * withdraw either waits behind this transaction or has already ended the
   * row, in which case this returns null and finalize refuses.
   */
  /**
   * The transaction-scoped advisory lock on the pet — the FIRST lock finalize
   * takes, before `lockLiveCustodyRow` (WU5 review, lock order). Finalize
   * locked the custody row and then closed every live row (the titular's
   * owner row among them); the titular's withdraw locked the owner row and
   * then closed the custody row. Two transactions, the same two row locks,
   * opposite orders: a deadlock Postgres breaks with 40P01. Both now take
   * this lock first — same key as RehomeRepository.acquirePetAdvisoryLock
   * and the chip-match / return-to-owner / cross-org writers — and the row
   * locks under it cannot form a cycle.
   */
  async acquirePetAdvisoryLock(petId: string, tx: Tx): Promise<void> {
    await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext(${petId}))`);
  },

  async lockLiveCustodyRow(ownershipId: string, tx: Tx): Promise<{ id: string } | null> {
    const [row] = await tx
      .select({ id: ownerships.id })
      .from(ownerships)
      .where(and(eq(ownerships.id, ownershipId), isNull(ownerships.endedAt)))
      .limit(1)
      .for("update");
    return row ?? null;
  },

  /**
   * Finds the active foster ownership row for a pet, or null if none.
   */
  async findActiveFoster(petId: string, tx?: Tx): Promise<FosterRow | null> {
    const client = tx ?? db;
    const [row] = await client
      .select({ id: ownerships.id, ownerUserId: ownerships.ownerUserId })
      .from(ownerships)
      .where(
        and(eq(ownerships.petId, petId), eq(ownerships.role, "foster"), isNull(ownerships.endedAt)),
      )
      .limit(1);

    return row ?? null;
  },

  /**
   * The adopter DNI oracle, guarded: per-organization ceiling before the read,
   * hashed pii_queried trail after it (adopter-dni-consult.ts). The raw lookup
   * is not on this repository on purpose — every caller goes through here.
   * The unguarded stub-profile lookup (no production caller since
   * org-pilot-pack) was removed with it.
   */
  consultAdopterAccountByDni,

  /**
   * Updates adoption eligibility and inserts the adoption_eligibility_set event.
   * Must be called inside a db.transaction().
   *
   * Case wiring (CASE_ATTACHMENT_RULES adoption_eligibility_set):
   *   - eligible=true  → opens an adoption_listing case (or attaches to one
   *                      already open for this org, degrading `opens` per the
   *                      rule) and writes case_id on the event atomically.
   *   - eligible=false → attaches to the org's open adoption_listing case if
   *                      one exists; otherwise the event inserts with no
   *                      case_id (silent no-op — matches the documented
   *                      `requires-open` override for this event/payload).
   * case_id is append-only on pet_events (DB trigger), so the decision must
   * be made before/at the same insert — it cannot be backfilled later.
   */
  async setEligibility(args: SetEligibilityArgs, tx: Tx): Promise<void> {
    await tx
      .update(pets)
      .set({
        adoptionEligible: args.eligible,
        adoptionIneligibleReason: args.eligible ? null : (args.ineligibleReason ?? null),
        adoptionIneligibleReasonNotes: args.eligible ? null : (args.ineligibleReasonNotes ?? null),
        adoptionIneligibleUntil: args.eligible ? null : args.ineligibleUntil,
        adoptionEligibilitySetAt: args.now,
        adoptionEligibilitySetByUserId: args.userId,
        updatedAt: args.now,
      })
      .where(eq(pets.id, args.petId));

    let caseId: string | null = null;
    const existingListingCase = await findOpenAdoptionListingCase(args.petId, args.orgId, tx);
    if (args.eligible) {
      if (existingListingCase) {
        caseId = existingListingCase.id;
      } else {
        const caseRow = await openCase(
          {
            kind: "adoption_listing",
            primarySubjectKind: "registered_pet",
            primaryPetId: args.petId,
            openedByUserId: args.userId,
            openedByOrganizationId: args.orgId,
            openedReason: { code: "adoption_listing_opened" },
          },
          tx,
        );
        caseId = caseRow.id;
      }
    } else {
      // requires-open (with silent no-op override): attach if a listing is
      // open, otherwise leave case_id null rather than rejecting the insert.
      caseId = existingListingCase?.id ?? null;
    }

    const payload = validateEventPayload("adoption_eligibility_set", {
      eligible: args.eligible,
      ineligible_reason: args.eligible ? null : (args.ineligibleReason ?? null),
      ineligible_reason_notes: args.eligible ? null : (args.ineligibleReasonNotes ?? null),
      ineligible_until: args.eligible
        ? null
        : args.ineligibleUntil
          ? args.ineligibleUntil.toISOString()
          : null,
      // Previous state captured by the use-case before calling setEligibility.
      previous_state: args.previousState ?? null,
    });

    await tx.insert(petEvents).values({
      petId: args.petId,
      eventType: "adoption_eligibility_set",
      occurredAt: args.now,
      recordedAt: args.now,
      recordedByUserId: args.userId,
      authorRole: "shelter",
      authorOrganizationId: args.orgId,
      authorVerified: args.orgVerified,
      payload,
      caseId,
    });
  },

  /**
   * Updates the listing status fields. No event emitted — listing is
   * shelf-curated metadata, not a pet-fact event.
   */
  async setListingStatus(args: SetListingStatusArgs, tx?: Tx): Promise<void> {
    const client = tx ?? db;

    if (args.action === "publish") {
      await client
        .update(pets)
        .set({
          adoptionListedAt: args.currentListedAt ?? args.now,
          adoptionListingPausedAt: null,
          updatedAt: args.now,
        })
        .where(eq(pets.id, args.petId));
    } else if (args.action === "unpublish") {
      await client
        .update(pets)
        .set({ adoptionListedAt: null, adoptionListingPausedAt: null, updatedAt: args.now })
        .where(eq(pets.id, args.petId));
    } else if (args.action === "pause") {
      await client
        .update(pets)
        .set({ adoptionListingPausedAt: args.now, updatedAt: args.now })
        .where(eq(pets.id, args.petId));
    } else {
      // unpause
      await client
        .update(pets)
        .set({ adoptionListingPausedAt: null, updatedAt: args.now })
        .where(eq(pets.id, args.petId));
    }
  },

  // ---------------------------------------------------------------------------
  // Bulk operations
  // ---------------------------------------------------------------------------

  /**
   * Batch ownership query for bulk eligibility writes.
   *
   * Returns only pets under active shelter_custody of the given org that are
   * NOT deceased — matches the single-pet requireAlivePetAccess scope.
   */
  async findBatchShelterPetsForEligibility(
    tokens: string[],
    orgId: string,
  ): Promise<BatchShelterPetForEligibility[]> {
    if (tokens.length === 0) return [];
    return db
      .select({ petId: pets.id, publicToken: pets.publicToken })
      .from(pets)
      .innerJoin(ownerships, eq(ownerships.petId, pets.id))
      .where(
        and(
          inArray(pets.publicToken, tokens),
          eq(ownerships.ownerOrganizationId, orgId),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
          ne(pets.status, "deceased"),
        ),
      );
  },

  /**
   * Batch ownership query for bulk listing publish/unpublish.
   *
   * Fetches the extra columns needed to evaluate publish guards (D18–D21)
   * per pet in the loop. Same scope as findBatchShelterPetsForEligibility.
   */
  async findBatchShelterPetsForListing(
    tokens: string[],
    orgId: string,
  ): Promise<BatchShelterPetForListing[]> {
    if (tokens.length === 0) return [];
    return db
      .select({
        petId: pets.id,
        publicToken: pets.publicToken,
        adoptionListedAt: pets.adoptionListedAt,
        status: pets.status,
        adoptionEligible: pets.adoptionEligible,
        inCustodyDispute: pets.inCustodyDispute,
        rabiesObservationStatus: pets.rabiesObservationStatus,
      })
      .from(pets)
      .innerJoin(ownerships, eq(ownerships.petId, pets.id))
      .where(
        and(
          inArray(pets.publicToken, tokens),
          eq(ownerships.ownerOrganizationId, orgId),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
          ne(pets.status, "deceased"),
        ),
      );
  },

  /**
   * Atomically updates pet eligibility columns and inserts an
   * adoption_eligibility_set event using insertEventIdempotent.
   *
   * Differs from setEligibility: uses idempotency-key deduplication so
   * re-submitting the same bulkActionId is a safe no-op (wasNoop=true).
   * The previous_state is null for the bulk path (performance: no pre-load).
   *
   * Must be called inside a db.transaction().
   */
  async setBulkEligibilityIdempotent(
    args: SetBulkEligibilityIdempotentArgs,
    tx: Tx,
  ): Promise<{ wasNoop: boolean }> {
    // UPDATE pets eligibility columns (last-write-wins — idempotent on retry).
    await tx
      .update(pets)
      .set({
        adoptionEligible: args.eligible,
        adoptionIneligibleReason: args.eligible ? null : (args.ineligibleReason ?? null),
        adoptionIneligibleReasonNotes: args.eligible ? null : (args.ineligibleReasonNotes ?? null),
        adoptionIneligibleUntil: args.eligible ? null : args.ineligibleUntil,
        adoptionEligibilitySetAt: args.now,
        adoptionEligibilitySetByUserId: args.userId,
        updatedAt: args.now,
      })
      .where(eq(pets.id, args.petId));

    const payload = validateEventPayload("adoption_eligibility_set", {
      eligible: args.eligible,
      ineligible_reason: args.eligible ? null : (args.ineligibleReason ?? null),
      ineligible_reason_notes: args.eligible ? null : (args.ineligibleReasonNotes ?? null),
      ineligible_until: args.eligible
        ? null
        : args.ineligibleUntil
          ? args.ineligibleUntil.toISOString()
          : null,
      // Bulk path: previous_state is null for performance (no per-pet pre-load).
      previous_state: null,
    });

    const { wasNoop } = await insertEventIdempotent(
      {
        petId: args.petId,
        eventType: "adoption_eligibility_set",
        occurredAt: args.now,
        recordedAt: args.now,
        recordedByUserId: args.userId,
        authorRole: "shelter",
        authorOrganizationId: args.orgId,
        authorVerified: args.orgVerified,
        payload,
        notes: null,
        clientIdempotencyKey: args.clientIdempotencyKey,
      },
      tx as Parameters<typeof insertEventIdempotent>[1],
    );

    return { wasNoop };
  },

  /**
   * Updates the listing content fields. No event emitted.
   */
  async updateListingContent(args: UpdateListingContentArgs, tx?: Tx): Promise<void> {
    const client = tx ?? db;
    await client
      .update(pets)
      .set({
        adoptionStory: args.story?.trim() || null,
        adoptionRequirements: args.requirements?.trim() || null,
        adoptionAgeBucket: (args.ageBucket ??
          null) as (typeof pets.$inferSelect)["adoptionAgeBucket"],
        adoptionSizeEstimate: (args.sizeEstimate ??
          null) as (typeof pets.$inferSelect)["adoptionSizeEstimate"],
        adoptionEnergyLevel: (args.energyLevel ??
          null) as (typeof pets.$inferSelect)["adoptionEnergyLevel"],
        adoptionGoodWithKids: args.goodWithKids ?? null,
        adoptionGoodWithDogs: args.goodWithDogs ?? null,
        adoptionGoodWithCats: args.goodWithCats ?? null,
        adoptionNeedsYard: args.needsYard ?? null,
        adoptionFeeArs: args.feeArs ?? null,
        updatedAt: new Date(),
      })
      .where(eq(pets.id, args.petId));
  },

  /**
   * Inserts an adoption_application_submitted event. Must be called inside
   * a db.transaction() so the org member fan-out can share the same tx.
   *
   * Case wiring (CASE_ATTACHMENT_RULES adoption_application_submitted, mode
   * "opens"): opens an adoption_application case scoped to (pet, applicant)
   * — or attaches to one already open for THIS applicant, degrading `opens`
   * per the rule. The scoping is per-applicant (not per-pet): the partial
   * unique index `cases_open_adoption_app_per_applicant_idx` allows multiple
   * distinct applicants to each have their own concurrent open
   * adoption_application case for the same pet, so a second application from
   * a DIFFERENT applicant opens a second, distinct case. case_id is
   * append-only on pet_events, so the decision is made atomically with this
   * insert.
   */
  async insertApplication(args: InsertApplicationArgs, tx: Tx): Promise<{ eventId: string }> {
    const payload = validateEventPayload("adoption_application_submitted", {
      applicant_user_id: args.userId,
      related_organization_id: args.orgId,
      housing_type: args.housingType,
      other_pets: args.otherPets,
      daily_routine: args.dailyRoutine,
      notes: args.notes,
      profile_sharing_consent_at: args.now.toISOString(),
      motivation: args.motivation ?? undefined,
      prior_pets: args.priorPets ?? undefined,
    });

    const existingApplicationCase = await findOpenAdoptionApplicationCase(
      args.petId,
      args.userId,
      tx,
    );
    const caseId = existingApplicationCase
      ? existingApplicationCase.id
      : (
          await openCase(
            {
              kind: "adoption_application",
              primarySubjectKind: "registered_pet",
              primaryPetId: args.petId,
              applicantUserId: args.userId,
              openedByUserId: args.userId,
              openedReason: { code: "adoption_application_submitted" },
            },
            tx,
          )
        ).id;

    const [eventRow] = await tx
      .insert(petEvents)
      .values({
        petId: args.petId,
        eventType: "adoption_application_submitted",
        occurredAt: args.now,
        recordedAt: args.now,
        recordedByUserId: args.userId,
        authorRole: "owner",
        authorOrganizationId: null,
        authorVerified: false,
        payload,
        caseId,
      })
      .returning({ id: petEvents.id });

    return { eventId: eventRow.id };
  },

  /**
   * Finds admin/coordinator members of an org to fan-out notifications to.
   */
  async findOrgMembersForNotify(orgId: string, tx?: Tx): Promise<{ userId: string }[]> {
    const client = tx ?? db;
    const rows = await client.execute<{ user_id: string }>(sql`
      SELECT user_id
      FROM organization_memberships
      WHERE organization_id = ${orgId}
        AND left_at IS NULL
        AND role IN ('admin', 'coordinator')
      LIMIT 25
    `);
    return rows.map((r) => ({ userId: r.user_id }));
  },

  /**
   * Loads a pending application for org-side review (approve/reject/info-request).
   * Verifies the pet is under active shelter_custody of the given org.
   *
   * PII fix (Item 27): projects ONLY the fields callers need. The full event
   * payload (which may contain applicant name/phone/address/DNI from the
   * adoption_application_submitted event) is kept in the immutable event log
   * but is never returned to callers. applicantUserId is the single PII field
   * the review and notification flows legitimately require.
   */
  async findApplicationForReview(
    applicationEventId: string,
    organizationId: string,
    tx?: Tx,
  ): Promise<
    | {
        application: ApplicationReviewShape;
        pet: { id: string; name: string; publicToken: string };
      }
    | { error: string }
  > {
    const client = tx ?? db;
    const [row] = await client
      .select({
        applicationId: petEvents.id,
        // Extract only applicant_user_id from the payload — the single field
        // callers need for notification routing. Name/phone/address/DNI stay
        // in the immutable event log and are never returned.
        applicantUserId: sql<string | null>`${petEvents.payload}->>'applicant_user_id'`,
        petId: pets.id,
        petName: pets.name,
        petPublicToken: pets.publicToken,
      })
      .from(petEvents)
      .innerJoin(pets, eq(pets.id, petEvents.petId))
      .innerJoin(ownerships, eq(ownerships.petId, pets.id))
      .where(
        and(
          eq(petEvents.id, applicationEventId),
          eq(petEvents.eventType, "adoption_application_submitted"),
          eq(ownerships.ownerOrganizationId, organizationId),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
        ),
      )
      .limit(1);

    if (!row) {
      return { error: "Postulación no encontrada o no pertenece a tu organización." };
    }

    // Check: already resolved?
    const decided = await client.execute<{ id: string }>(sql`
      SELECT id FROM pet_events
      WHERE pet_id = ${row.petId}
        AND event_type = 'adoption_application_resolved'
        AND payload->>'application_event_id' = ${applicationEventId}
      LIMIT 1
    `);
    if (decided.length > 0) {
      return { error: "Esta postulación ya fue resuelta." };
    }

    // Check: pet already finalized?
    const finalized = await client.execute<{ id: string }>(sql`
      SELECT id FROM pet_events
      WHERE pet_id = ${row.petId}
        AND event_type = 'adoption_finalized'
      LIMIT 1
    `);
    if (finalized.length > 0) {
      return { error: "Esta mascota ya fue adoptada — no es posible revisar postulaciones." };
    }

    return {
      application: { id: row.applicationId, applicantUserId: row.applicantUserId },
      pet: { id: row.petId, name: row.petName, publicToken: row.petPublicToken },
    };
  },

  /**
   * Loads an APPROVED application for the finalize-from-application flow.
   *
   * Verifies, org-scoped:
   *   - the event exists, is an adoption_application_submitted for THIS pet
   *   - the pet is under active shelter_custody of the given org
   *   - the application has a resolved event with outcome=approved
   *   - the applicant has an account (applicant_user_id present)
   *
   * Returns the applicant's real user id (the account they applied with) so
   * finalization transfers ownership directly to it — the pet then appears in
   * the adopter's /mis-mascotas immediately. PII-safe: only applicant_user_id
   * is projected, never the full application payload.
   */
  async findApprovedApplicationForFinalize(
    applicationEventId: string,
    organizationId: string,
    petId: string,
    tx?: Tx,
  ): Promise<{ applicantUserId: string } | { error: string }> {
    const client = tx ?? db;
    const [row] = await client
      .select({
        applicantUserId: sql<string | null>`${petEvents.payload}->>'applicant_user_id'`,
      })
      .from(petEvents)
      .innerJoin(pets, eq(pets.id, petEvents.petId))
      .innerJoin(ownerships, eq(ownerships.petId, pets.id))
      .where(
        and(
          eq(petEvents.id, applicationEventId),
          eq(petEvents.eventType, "adoption_application_submitted"),
          eq(petEvents.petId, petId),
          eq(ownerships.ownerOrganizationId, organizationId),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
        ),
      )
      .limit(1);

    if (!row) {
      return { error: "Postulación no encontrada o no pertenece a tu organización." };
    }

    const approved = await client.execute<{ id: string }>(sql`
      SELECT id FROM pet_events
      WHERE pet_id = ${petId}
        AND event_type = 'adoption_application_resolved'
        AND payload->>'application_event_id' = ${applicationEventId}
        AND payload->>'outcome' = 'approved'
      LIMIT 1
    `);
    if (approved.length === 0) {
      return {
        error: "La postulación seleccionada no está aprobada. Aprobala antes de finalizar.",
      };
    }

    if (!row.applicantUserId) {
      return { error: "La postulación no tiene un postulante con cuenta miMAR." };
    }

    return { applicantUserId: row.applicantUserId };
  },

  /**
   * Finds all pending applications for a pet (for auto-rejection cascade).
   * Excludes a specific adopter's application (the one who just adopted);
   * `null` excludes nobody — the titular's withdraw cascade closes every one.
   */
  async findPendingApplicationsExcluding(
    petId: string,
    excludeUserId: string | null,
    tx: Tx,
  ): Promise<{ applicationId: string; applicantUserId: string }[]> {
    const excludeClause = excludeUserId
      ? sql`AND e.payload->>'applicant_user_id' <> ${excludeUserId}`
      : sql``;
    const rows = await tx.execute<{ application_id: string; applicant_user_id: string }>(sql`
      SELECT e.id::text AS application_id,
             e.payload->>'applicant_user_id' AS applicant_user_id
      FROM pet_events e
      WHERE e.pet_id = ${petId}
        AND e.event_type = 'adoption_application_submitted'
        ${excludeClause}
        AND NOT EXISTS (
          SELECT 1 FROM pet_events d
          WHERE d.pet_id = e.pet_id
            AND d.event_type = 'adoption_application_resolved'
            AND d.payload->>'application_event_id' = e.id::text
        )
    `);
    return rows.map((r) => ({
      applicationId: r.application_id,
      applicantUserId: r.applicant_user_id,
    }));
  },

  /**
   * Applications the org APPROVED but never finalized — the ones an adopter
   * is still waiting on when a listing closes under them (the titular's
   * withdraw, rehome-by-titular). Their approval stays the single resolution
   * on the spine; what closes is their case, and what they get is a word.
   */
  async findApprovedUnfinalizedApplications(
    petId: string,
    tx: Tx,
  ): Promise<{ applicationId: string; applicantUserId: string }[]> {
    const rows = await tx.execute<{ application_id: string; applicant_user_id: string }>(sql`
      SELECT e.id::text AS application_id,
             e.payload->>'applicant_user_id' AS applicant_user_id
      FROM pet_events e
      WHERE e.pet_id = ${petId}
        AND e.event_type = 'adoption_application_submitted'
        AND EXISTS (
          SELECT 1 FROM pet_events a
          WHERE a.pet_id = e.pet_id
            AND a.event_type = 'adoption_application_resolved'
            AND a.payload->>'application_event_id' = e.id::text
            AND a.payload->>'outcome' = 'approved'
        )
        AND NOT EXISTS (
          SELECT 1 FROM pet_events f
          WHERE f.pet_id = e.pet_id
            AND f.event_type = 'adoption_finalized'
            AND f.payload->>'adopted_from_application_id' = e.id::text
        )
    `);
    return rows.map((r) => ({
      applicationId: r.application_id,
      applicantUserId: r.applicant_user_id,
    }));
  },

  /**
   * Finds the open custody_episode case for a pet, or null if none.
   * Used by the finalize-adoption use-case to get the case id before the tx.
   */
  async findOpenCustodyCase(petId: string): Promise<{ id: string } | null> {
    return findOpenCaseForPetAndKind(petId, "custody_episode");
  },

  /**
   * Composite atomic write for finalizing an adoption. Must be called inside a
   * db.transaction().
   *
   * Moved to adoption-finalize-writer.ts (2026-08-21) — the header there says
   * why. Kept as a delegating member so every caller and every test double
   * still reaches it through the repository.
   */
  insertAdoptionFinalized,

  /**
   * Inserts an adoption_application_resolved event (approve or reject),
   * attached to the application's open case (CASE_ATTACHMENT_RULES: mode
   * `requires-open`). A REJECTION also closes that case in the same
   * transaction (`cancelled`, with a `case_closed` note) unless `closeCase:
   * false`. An APPROVAL leaves it open on purpose — the adopter is still
   * waiting for a finalize, which closes it `resolved`, or for the cascade
   * that tells them it will not happen (application-case-close.ts).
   * Must be called inside a db.transaction().
   */
  async resolveApplication(args: ResolveApplicationArgs, tx: Tx): Promise<void> {
    const payload = validateEventPayload("adoption_application_resolved", {
      application_event_id: args.applicationEventId,
      reviewer_user_id: args.reviewerUserId,
      outcome: args.outcome,
      reason: args.outcome === "rejected" ? (args.reason ?? "manual_rejection") : undefined,
      auto_generated: args.autoGenerated ?? false,
      notes: args.notes ?? null,
    });

    const appCase = await findOpenCaseForApplication(args.petId, args.applicationEventId, tx);

    await tx.insert(petEvents).values({
      petId: args.petId,
      eventType: "adoption_application_resolved",
      occurredAt: args.now,
      recordedAt: args.now,
      recordedByUserId: args.reviewerUserId,
      authorRole: args.author?.role ?? "shelter",
      authorOrganizationId: args.author ? args.author.organizationId : args.orgId,
      authorVerified: args.author?.verified ?? args.orgVerified,
      payload,
      caseId: appCase?.id ?? null,
    });

    if (appCase && args.outcome !== "approved" && args.closeCase !== false) {
      await closeApplicationCase(
        {
          caseId: appCase.id,
          reason: "cancelled",
          closedByUserId: args.reviewerUserId,
          outcome: args.outcome,
          note: applicationCloseNote({
            outcome: args.outcome,
            reason: args.reason,
            autoGenerated: args.autoGenerated,
          }),
          now: args.now,
        },
        tx,
      );
    }
  },

  /**
   * Loads a pending application for the APPLICANT-side withdrawal flow.
   *
   * Verifies, in one read:
   *   - the event exists and is an adoption_application_submitted
   *   - the caller (applicantUserId) is the submitter (ownership guard)
   *   - the application is still unresolved (no adoption_application_resolved
   *     for it) — same NOT EXISTS pending-derivation the postulaciones list
   *     and the org review query use.
   *
   * Returns the application + pet (id, name) + the shelter org id (for the
   * org-side notification), or an error string.
   */
  async findApplicationForWithdrawal(
    applicationEventId: string,
    applicantUserId: string,
    tx?: Tx,
  ): Promise<
    | {
        application: { id: string };
        pet: { id: string; name: string };
        org: { id: string; publicToken: string; displayName: string };
      }
    | { error: string }
  > {
    const client = tx ?? db;
    const [row] = await client
      .select({
        applicationId: petEvents.id,
        applicantUserId: sql<string>`${petEvents.payload}->>'applicant_user_id'`,
        petId: pets.id,
        petName: pets.name,
        orgId: organizations.id,
        orgPublicToken: organizations.publicToken,
        orgDisplayName: organizations.displayName,
      })
      .from(petEvents)
      .innerJoin(pets, eq(pets.id, petEvents.petId))
      .innerJoin(
        ownerships,
        and(
          eq(ownerships.petId, pets.id),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
        ),
      )
      .innerJoin(organizations, eq(organizations.id, ownerships.ownerOrganizationId))
      .where(
        and(
          eq(petEvents.id, applicationEventId),
          eq(petEvents.eventType, "adoption_application_submitted"),
        ),
      )
      .limit(1);

    if (!row) {
      return { error: "No encontramos esta postulación." };
    }
    if (row.applicantUserId !== applicantUserId) {
      return { error: "Solo podés retirar tus propias postulaciones." };
    }

    // Already resolved (approved / rejected / closed / withdrawn)?
    const decided = await client.execute<{ id: string }>(sql`
      SELECT id FROM pet_events
      WHERE pet_id = ${row.petId}
        AND event_type = 'adoption_application_resolved'
        AND payload->>'application_event_id' = ${applicationEventId}
      LIMIT 1
    `);
    if (decided.length > 0) {
      return { error: "Esta postulación ya fue resuelta y no se puede retirar." };
    }

    // Pet already adopted? A finalize cascade should already have resolved
    // this application, but defend anyway.
    const finalized = await client.execute<{ id: string }>(sql`
      SELECT id FROM pet_events
      WHERE pet_id = ${row.petId} AND event_type = 'adoption_finalized'
      LIMIT 1
    `);
    if (finalized.length > 0) {
      return { error: "Esta postulación ya fue resuelta y no se puede retirar." };
    }

    return {
      application: { id: row.applicationId },
      pet: { id: row.petId, name: row.petName },
      org: {
        id: row.orgId,
        publicToken: row.orgPublicToken,
        displayName: row.orgDisplayName,
      },
    };
  },

  /**
   * Inserts a lightweight `note_added` marker (kind=adoption_info_requested)
   * recording that the shelter probed an adoption application for more info.
   * Reuses note_added (category=system) rather than a new event type — the
   * marker carries the application_event_id so both sides can derive the
   * "info requested" state (applicant: "te pidieron más info"; org: probed row).
   *
   * Attached to the application's pet, authored by the shelter org. Idempotent
   * by intent at the action layer (a re-probe simply appends a newer marker —
   * the derivation reads the latest).
   */
  async insertInfoRequestedNote(
    args: {
      petId: string;
      applicationEventId: string;
      reviewerUserId: string;
      orgId: string;
      orgVerified: boolean;
      message: string;
      now: Date;
    },
    tx?: Tx,
  ): Promise<void> {
    const client = tx ?? db;
    // The message lives under its own key (T3-A2b): it is about the APPLICANT,
    // and erasure reaches it through application_event_id. `text` carries a
    // fixed label, so generic note readers never render the shelter's words.
    const payload = validateEventPayload("note_added", {
      category: "system",
      text: INFO_REQUEST_NOTE_LABEL,
      info_request_message: args.message,
      kind: "adoption_info_requested",
      application_event_id: args.applicationEventId,
    });

    await client.insert(petEvents).values({
      petId: args.petId,
      eventType: "note_added",
      occurredAt: args.now,
      recordedAt: args.now,
      recordedByUserId: args.reviewerUserId,
      authorRole: "shelter",
      authorOrganizationId: args.orgId,
      authorVerified: args.orgVerified,
      payload,
    });
  },

  /**
   * Inserts an adoption_application_resolved event with outcome=withdrawn.
   * The author is the APPLICANT (owner role, no org) — distinct from the
   * shelter-authored approve/reject path. Attaches to and CLOSES the
   * application's case (`cancelled`) like resolveApplication does; it is the
   * same terminal event. Must be called inside a db.transaction().
   */
  async withdrawApplication(
    args: { petId: string; applicationEventId: string; applicantUserId: string; now: Date },
    tx: Tx,
  ): Promise<void> {
    const payload = validateEventPayload("adoption_application_resolved", {
      application_event_id: args.applicationEventId,
      reviewer_user_id: args.applicantUserId,
      outcome: "withdrawn",
      auto_generated: false,
      notes: null,
    });

    const appCase = await findOpenAdoptionApplicationCase(args.petId, args.applicantUserId, tx);

    await tx.insert(petEvents).values({
      petId: args.petId,
      eventType: "adoption_application_resolved",
      occurredAt: args.now,
      recordedAt: args.now,
      recordedByUserId: args.applicantUserId,
      authorRole: "owner",
      authorOrganizationId: null,
      authorVerified: false,
      payload,
      caseId: appCase?.id ?? null,
    });

    if (appCase) {
      await closeApplicationCase(
        {
          caseId: appCase.id,
          reason: "cancelled",
          closedByUserId: args.applicantUserId,
          outcome: "withdrawn",
          note: applicationCloseNote({ outcome: "withdrawn" }),
          now: args.now,
        },
        tx,
      );
    }
  },

  // ---------------------------------------------------------------------------
  // Reversal (mirrors finalize in reverse — see reverse-adoption.ts)
  // ---------------------------------------------------------------------------

  /**
   * Finds a pet by public token with NO ownership/org constraint — unlike
   * findShelterPet, the reversal flow's caller (the finalizing org) may no
   * longer hold any active ownership row on this pet at all (that is exactly
   * what a finalized adoption does: it ends the org's shelter_custody row).
   */
  async findPetByToken(
    petPublicToken: string,
    tx?: Tx,
  ): Promise<{ id: string; name: string } | null> {
    const client = tx ?? db;
    const [row] = await client
      .select({ id: pets.id, name: pets.name })
      .from(pets)
      // Art. 16: an erased pet answers like a token that never existed.
      .where(unerasedPetByToken(petPublicToken))
      .limit(1);
    return row ?? null;
  },

  /**
   * The reversibility gate. Finds the LATEST adoption_finalized event
   * authored by THIS organization for this pet, and verifies:
   *   1. it exists (this org actually finalized an adoption for this pet);
   *   2. it has not already been reversed (no adoption_reversed event
   *      references it via reverted_finalization_event_id) — idempotency;
   *   3. the pet's current active ownership is still that same adopter,
   *      role='owner' — defends against a stale finalize (custody moved on
   *      via a later cycle) and doubles as the second double-reverse guard
   *      (after a first reversal the active role is shelter_custody, not
   *      owner, so this check alone would already reject a repeat call).
   *
   * Read-only — safe to call from a server component for UI gating (see the
   * org pet ficha's "ya no está bajo tu custodia" branch) as well as from the
   * use-case as the authoritative pre-write check.
   */
  async findReversibleAdoption(
    petId: string,
    organizationId: string,
    tx?: Tx,
  ): Promise<ReversibleAdoptionResult> {
    const client = tx ?? db;

    const [finalizeEvent] = await client
      .select({
        id: petEvents.id,
        adopterUserId: sql<string | null>`${petEvents.payload}->>'adopter_user_id'`,
      })
      .from(petEvents)
      .where(
        and(
          eq(petEvents.petId, petId),
          eq(petEvents.eventType, "adoption_finalized"),
          eq(petEvents.authorOrganizationId, organizationId),
        ),
      )
      .orderBy(desc(petEvents.occurredAt))
      .limit(1);

    if (!finalizeEvent) {
      return {
        ok: false,
        error: "Esta organización no finalizó ninguna adopción para esta mascota.",
      };
    }

    const reversed = await client.execute<{ id: string }>(sql`
      SELECT id FROM pet_events
      WHERE pet_id = ${petId}
        AND event_type = 'adoption_reversed'
        AND payload->>'reverted_finalization_event_id' = ${finalizeEvent.id}
      LIMIT 1
    `);
    if (reversed.length > 0) {
      return { ok: false, error: "Esta adopción ya fue revertida." };
    }

    const ownerQuery = client
      .select({ id: ownerships.id, ownerUserId: ownerships.ownerUserId, petName: pets.name })
      .from(ownerships)
      .innerJoin(pets, eq(pets.id, ownerships.petId))
      .where(
        and(eq(ownerships.petId, petId), eq(ownerships.role, "owner"), isNull(ownerships.endedAt)),
      )
      .limit(1);
    // Inside the reversal transaction the adopter's row is read FOR UPDATE (of
    // the ownership row only, never the joined pet): the answer is the one the
    // guarded close below acts on, and a hand-off that closes it concurrently
    // has to wait for this transaction instead of slipping in between. Outside
    // a transaction (the ficha's UI gate) there is nothing to hold a lock for.
    const [ownerRow] = tx ? await ownerQuery.for("update", { of: ownerships }) : await ownerQuery;

    if (
      !ownerRow ||
      !finalizeEvent.adopterUserId ||
      ownerRow.ownerUserId !== finalizeEvent.adopterUserId
    ) {
      return { ok: false, error: ADOPTER_NO_LONGER_HOLDS_ERROR };
    }

    // One live ORG custody per pet (0195). The reversal restores THIS org's
    // shelter_custody row; if another org took the animal in since the
    // adoption (a found-pet intake), that insert would hit the index.
    if (await findLiveOrgShelterCustody(petId, client)) {
      return { ok: false, error: ORG_CUSTODY_TAKEN_ERROR };
    }

    return {
      ok: true,
      finalizeEventId: finalizeEvent.id,
      adopterOwnershipId: ownerRow.id,
      adopterUserId: ownerRow.ownerUserId,
      petName: ownerRow.petName,
    };
  },

  /**
   * Composite atomic write for reversing an adoption. Must be called inside a
   * db.transaction(). Mirrors insertAdoptionFinalized in reverse:
   *   - close the adopter's `owner` ownership row
   *   - insert a fresh `shelter_custody` ownership row for the finalizing org
   *   - force the pet UN-LISTED (adoption_listed_at / paused_at → null) — PO
   *     semantics: reversal never auto-relists.
   *
   *     This used to be load-bearing: finalize did NOT clear the field, so
   *     restoring an active shelter_custody row would resurrect whatever
   *     adoption_listed_at predated the finalize and the pet would reappear on
   *     /adoptar (queryAdoptionListing's D-guards only check listedAt + active
   *     shelter_custody). Finalize now clears it — see insertAdoptionFinalized
   *     — so this write is DEFENSIVE, not load-bearing. Keep it: it also covers
   *     a re-list that happened between finalize and reversal.
   *   - insert the adoption_reversed event, referencing the finalize event id
   */
  async insertAdoptionReversed(
    args: InsertAdoptionReversedArgs,
    tx: Tx,
  ): Promise<{ eventId: string }> {
    const { petId, userId, orgId, orgVerified, adopterOwnershipId, finalizeEventId, reason, now } =
      args;

    // Close the adopter's owner ownership row — ONLY while it is still live
    // and still an owner row (audit K, W1). Keyed on the id alone, a row some
    // other hand-off had already closed was re-closed here: its `ended_at`
    // rewritten to this instant, and a shelter_custody opened over whoever
    // holds the pet now. Zero rows matched means the adopter no longer holds
    // the pet, and the whole reversal is refused.
    const closedAdopterRows = await tx
      .update(ownerships)
      .set({ endedAt: now })
      .where(
        and(
          eq(ownerships.id, adopterOwnershipId),
          eq(ownerships.role, "owner"),
          isNull(ownerships.endedAt),
        ),
      )
      .returning({ id: ownerships.id });
    if (closedAdopterRows.length === 0) {
      throw new ReversalRefused(ADOPTER_NO_LONGER_HOLDS_ERROR);
    }

    // Restore shelter_custody ownership to the finalizing org.
    await tx.insert(ownerships).values({
      petId,
      ownerOrganizationId: orgId,
      role: "shelter_custody",
      startedAt: now,
      transferredFromId: adopterOwnershipId,
    });

    // Force UN-LISTED (see method doc above).
    await tx
      .update(pets)
      .set({ adoptionListedAt: null, adoptionListingPausedAt: null, updatedAt: now })
      .where(eq(pets.id, petId));

    const payload = validateEventPayload("adoption_reversed", {
      actor: "shelter",
      reason,
      reverted_finalization_event_id: finalizeEventId,
    });

    const [event] = await tx
      .insert(petEvents)
      .values({
        petId,
        eventType: "adoption_reversed",
        occurredAt: now,
        recordedAt: now,
        recordedByUserId: userId,
        authorRole: "shelter",
        authorOrganizationId: orgId,
        authorVerified: orgVerified,
        payload,
      })
      .returning({ id: petEvents.id });

    return { eventId: event.id };
  },
};
