// Closing an `adoption_application` case — the one place that knows WHEN the
// application's process ends and what the applicant reads under "Expediente
// cerrado".
//
// THE BUG THIS RETIRES (rehome verify report S-6, 2026-08-22). Every resolver
// wrote `adoption_application_resolved` and left the case OPEN: reject, the
// applicant's withdraw and finalize's auto-rejections all parked an "open"
// row in every queue for a decision already taken, and finalize never closed
// the ADOPTER's own case either. The rehome withdraw and the death cascade
// closed theirs explicitly, which is how the gap became visible.
//
// WHEN THE CASE CLOSES — and when it deliberately does NOT:
//   · rejected / withdrawn          → `cancelled`, here, in the resolver's tx
//   · finalized (the adopter's own) → `resolved`, in the finalize writer's tx
//   · auto-rejected by a finalize   → `cancelled`, through the resolver
//   · APPROVED                      → stays OPEN. Approval is not the end of
//     the process: the adopter is waiting for a finalize that may never come,
//     and the titular's withdraw / the death cascade close the case with a
//     note that says so (__tests__/rehome-withdraw-flow.test.ts pins the
//     case as open after approval, on purpose). Closing it at approval would
//     take that note away from the one applicant who most needs it.
//
// Lives beside the repository and the finalize writer instead of inside
// either: the repository imports the writer, so the writer cannot import the
// repository back.

import { and, eq, sql } from "drizzle-orm";

import { caseEvents, type db, petEvents } from "@/db";
import { closeCaseOwned, findOpenAdoptionApplicationCase } from "@/lib/infra/case-helpers";

type Tx = Parameters<Parameters<typeof db.transaction>[0]>[0];

/** What the close records in `case_events.payload.adoption_decision`. */
export type ApplicationCloseOutcome = "rejected" | "withdrawn" | "finalized";

/**
 * The open `adoption_application` case an application hangs off, found the
 * way every other reader finds it: by (pet, applicant) — the partial unique
 * index `cases_open_adoption_app_per_applicant_idx` allows at most one. The
 * applicant is read from the SUBMITTED event's own payload, so a caller that
 * knows only the application event id (every resolver does) needs nothing
 * more. Null when the submit predates case wiring or the case already closed.
 */
export async function findOpenCaseForApplication(
  petId: string,
  applicationEventId: string,
  tx: Tx,
): Promise<{ id: string } | null> {
  const [submitted] = await tx
    .select({ applicantUserId: sql<string | null>`${petEvents.payload}->>'applicant_user_id'` })
    .from(petEvents)
    .where(and(eq(petEvents.id, applicationEventId), eq(petEvents.petId, petId)))
    .limit(1);
  if (!submitted?.applicantUserId) return null;
  return findOpenAdoptionApplicationCase(petId, submitted.applicantUserId, tx);
}

/**
 * Close an application's case and leave the prose the applicant reads. OWNED,
 * not merely idempotent: `case_events` is append-only by trigger, so the note
 * is written only when THIS caller's UPDATE was the one that closed the row
 * (the same discipline as rehome-repository.ts's closeCaseWithNote).
 *
 * `payload.adoption_decision` mirrors rehome's `rehome_decision` for a reader
 * that wants to title the entry by what was decided; none does yet.
 */
export async function closeApplicationCase(
  args: {
    caseId: string;
    reason: "resolved" | "cancelled";
    closedByUserId: string;
    outcome: ApplicationCloseOutcome;
    note: string;
    now: Date;
  },
  tx: Tx,
): Promise<void> {
  const { won } = await closeCaseOwned(
    { caseId: args.caseId, reason: args.reason, closedByUserId: args.closedByUserId },
    tx,
  );
  if (!won) return;
  await tx.insert(caseEvents).values({
    caseId: args.caseId,
    entryType: "case_closed",
    notes: args.note,
    recordedByUserId: args.closedByUserId,
    occurredAt: args.now,
    payload: { adoption_decision: args.outcome },
  });
}

/** The sentence under "Expediente cerrado" on an application's timeline. */
export function applicationCloseNote(args: {
  outcome: ApplicationCloseOutcome;
  reason?: string;
  autoGenerated?: boolean;
}): string {
  if (args.outcome === "finalized") {
    return "La adopción se concretó: la mascota ya tiene nuevo hogar.";
  }
  if (args.outcome === "withdrawn") return "Quien postuló retiró la postulación.";
  if (args.reason === "another_application_finalized") {
    return "La mascota encontró hogar por otra postulación; esta postulación quedó cerrada.";
  }
  if (args.autoGenerated) return "La postulación se cerró automáticamente.";
  return "La organización no avanzó con la postulación.";
}
