-- ────────────────────────────────────────────────────────────────────────────
-- 0274_condition_at_intake.sql
-- The database half of the new event type condition_at_intake_recorded
-- (vet-visit-record, work unit 3). Event types are TEXT, so the type itself
-- needs no DDL; two things do.
--
-- 1. AT MOST ONE INTAKE PER VISIT
-- ---------------------------------------------------------------------------
-- recordConditionAtIntake reads the visit first and refuses a second intake
-- with a sentence; this partial unique index is what holds under concurrency
-- (two submits of DIFFERENT intakes racing past that read). A replay of the
-- SAME intake never reaches it: its insert is arbitrated by
-- pet_events_idempotency_idx (ON CONFLICT DO NOTHING on the idempotency key),
-- which Postgres checks as the arbiter before any other unique index.
-- Partial on the event type and a non-null visit: every other row is outside
-- it, so the index stays as small as the number of intakes.
--
-- 2. WHAT AN ART. 16 ERASURE DOES TO ITS PAYLOAD
-- ---------------------------------------------------------------------------
-- pii.pet_event_redaction_rules must equal redactionRules() from
-- lib/events/payload-privacy.ts both ways (lint:subject-rights). The new type
-- adds four rows, generated by the same code 0240 used
-- (scripts/generate-pet-event-redaction-rules.ts' renderSeed, over the rules
-- the live table was missing): the vet's two prose fields are kept as a
-- professional act and sentinelled otherwise (author-gated), and a point on
-- the row is coarsened like every other type's. Modality, general condition
-- and vitals are compliance facts — facts about the animal — and need no row.
-- ON CONFLICT DO NOTHING: re-running this file changes nothing.
--
-- Idempotent. Forward-only. Ends in a post-condition that raises.
-- Applying it to a remote DB is Ignacio-gated.
-- ────────────────────────────────────────────────────────────────────────────

CREATE UNIQUE INDEX IF NOT EXISTS pet_events_one_intake_per_visit
  ON public.pet_events (visit_id)
  WHERE event_type = 'condition_at_intake_recorded' AND visit_id IS NOT NULL;

insert into pii.pet_event_redaction_rules
  (event_type, key_path, transform, author_gated, party_keys)
values
  ('condition_at_intake_recorded', array['#location_lat'], 'coarsen_point', false, null),
  ('condition_at_intake_recorded', array['#location_lng'], 'coarsen_point', false, null),
  ('condition_at_intake_recorded', array['findings'], 'sentinel', true, null),
  ('condition_at_intake_recorded', array['presenting_complaint'], 'sentinel', true, null)
on conflict (event_type, key_path) do nothing;

-- ---------------------------------------------------------------------------
-- Post-condition
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
     WHERE schemaname = 'public'
       AND tablename = 'pet_events'
       AND indexname = 'pet_events_one_intake_per_visit'
       AND indexdef LIKE 'CREATE UNIQUE INDEX%'
  ) THEN
    RAISE EXCEPTION 'Migration 0274 did not close: pet_events_one_intake_per_visit is missing or not unique';
  END IF;
  IF (SELECT count(*) FROM pii.pet_event_redaction_rules
       WHERE event_type = 'condition_at_intake_recorded') <> 4 THEN
    RAISE EXCEPTION 'Migration 0274 did not close: condition_at_intake_recorded must carry exactly 4 redaction rules';
  END IF;
END
$$;
