// maplibre worker wiring fence.
//
// WHAT WENT WRONG, so the fence's shape makes sense. maplibre-gl 6 asks for its
// worker at runtime via `new URL('./maplibre-gl-worker.mjs', import.meta.url)`.
// No bundler resolves that statically, so webpack emits no asset — measured on
// this tree: after a clean `pnpm build`, `find .next -iname "*worker*"` returns
// nothing. The fetch then does NOT 404; Next serves the app's own HTML with a
// 200, the worker executes HTML as JavaScript and dies without a word. The map
// registers every layer and source and renders ZERO features, with an empty
// console. It cost a full day of ruling out the database, WebGL2, the load
// handler, legacy expressions and the CSP — every one of them a correct answer
// to the wrong question.
//
// WHY THIS FENCE DOES NOT CHECK FILE BYTES as its main job. `public/maplibre/`
// is generated by `prebuild`/`predev` and gitignored, so version drift between
// the copy and the installed package cannot survive a build. What CAN rot is
// the WIRING — and the way it rots is silent, which is the whole problem:
//
//   · a fifth `import("maplibre-gl")` added somewhere, bypassing the loader and
//     therefore `setWorkerUrl`. That component's map goes quiet, nothing else.
//   · `prebuild` dropped from package.json in a cleanup. The files stop being
//     generated and every map goes quiet at once.
//   · the URL constant and the copy destination drifting apart.
//   · a future maplibre reaching for a different file than the two copied.
//
// None of those produce an error anywhere. All four are checked below.
import { existsSync, globSync, readFileSync } from "node:fs";
import { join } from "node:path";

import {
  MAPLIBRE_PUBLIC_DIR,
  MAPLIBRE_WORKER_ASSETS,
  maplibreDistDir,
  maplibreVersion,
  sha,
  unknownRelativeImports,
} from "./copy-maplibre-worker";

const problems: string[] = [];

const LOADER = "lib/ui/maplibre-loader.ts";
const COPY_SCRIPT = "scripts/copy-maplibre-worker.ts";

/**
 * Any RUNTIME reference to the package, in any spelling.
 *
 * THE FIRST VERSION OF THIS MATCHED ONE CALL SHAPE — `import("maplibre-gl")` —
 * and adversarial review measured what walked past it: a static default import
 * (`import maplibregl from "maplibre-gl"`), a named one, a template literal, a
 * parenthesised argument, a deep subpath (`maplibre-gl/dist/maplibre-gl.mjs`,
 * legal: the package's exports map publishes `./dist/*`), `require()` through
 * `createRequire`, and a re-export barrel. The first of those is the one that
 * matters, because it is the form maplibre's own documentation shows — so it is
 * what the next person writes, and the fence would have waved it through while
 * CANON-531 said it could not.
 *
 * So: match the SPECIFIER wherever a module reference can carry it. Three
 * shapes, all over comment-stripped source.
 */
// The three quote characters. The backtick is a unicode escape so this
// file's own template literals below stay readable.
const Q = "[\"'\\u0060]";
const SPEC = "maplibre-gl(?:/[^\"'\\u0060]*)?";

const IMPORT_SHAPES: RegExp[] = [
  // `import ... from "x"`, `export ... from "x"`, and the bare side-effect form.
  new RegExp(`(?:^|[\\n;])\\s*(?:import|export)\\b[^;]*?${Q}${SPEC}${Q}`, "m"),
  // `import("x")`, tolerating wrapping parens and a template-literal specifier.
  new RegExp(`\\bimport\\s*\\(\\s*(?:\\()*\\s*${Q}${SPEC}${Q}`),
  // `require("x")` - reachable in this repo through createRequire.
  new RegExp(`\\brequire\\s*\\(\\s*${Q}${SPEC}${Q}`),
];

const CSS_ONLY = new RegExp(`^\\s*import\\s+${Q}maplibre-gl/dist/maplibre-gl\\.css${Q}\\s*;?\\s*$`);

/**
 * A SECOND, INDEPENDENT NET, because the first one is still a text match on a
 * specifier and specifiers can be spelled in ways nobody has thought of yet.
 * Whatever the import looks like, a component that builds a map ends up writing
 * `new <something>.Map(` or `new <something>.Marker(`. A file that does that and
 * does not go through the loader is a bypass by construction.
 *
 * The dot is what keeps this quiet: a bare `new Map()` is the JavaScript
 * builtin and is everywhere.
 */
const MAP_CONSTRUCTOR = /\bnew\s+[A-Za-z_$][\w$]*\.(?:Map|Marker)\s*\(/;

function loadsMapLibre(code: string): boolean {
  const lines = code.split("\n").filter((l) => !CSS_ONLY.test(l));
  const withoutCss = lines.join("\n");
  const withoutTypeOnly = withoutCss.replace(/(?:^|[\n;])\s*(?:import|export)\s+type\b[^;]*;/g, "");
  return IMPORT_SHAPES.some((re) => re.test(withoutTypeOnly));
}

/**
 * Characters after which a `/` starts a REGEX LITERAL rather than division.
 *
 * WITHOUT THIS THE STRIPPER DESYNCHRONISES AND CAN DELETE REAL CODE, which is
 * the one direction a fence may never fail in. Adversarial review measured it:
 *
 *     const QUOTE_RE = /[\"']/;
 *     const url = "https://tiles.example/x"; await import("maplibre-gl");
 *
 * the quote inside the character class opens a bogus string, it closes on the
 * quote of the URL, `https:` arrives at top level, `//` reads as a comment and
 * the import is deleted. Legal TypeScript, invisible to the fence. Measured
 * over this repo's own scan set: 16 files desynchronise today and none loses
 * code to it yet -- but the OTHER half of the same desync is already live,
 * because in those 16 files comments stop being stripped, so a commented-out
 * import would be reported as an offender. That is the fence punishing the
 * documentation, which is what this whole function exists to prevent.
 */
const REGEX_MAY_FOLLOW = new Set("=(,:[!&|?{};+-*%<>~^".split(""));

function lastSignificant(out: string[]): string {
  for (let i = out.length - 1; i >= 0; i--) {
    const c = out[i];
    if (c !== undefined && c.trim() !== "") return c;
  }
  return "";
}

/** End index of the regex literal at `start`, or -1 when it is not one. */
function endOfRegex(source: string, start: number): number {
  let i = start + 1;
  let inClass = false;
  while (i < source.length) {
    const c = source[i];
    if (c === "\\") {
      i += 2;
      continue;
    }
    if (c === "\n") return -1;
    if (c === "[") inClass = true;
    else if (c === "]") inClass = false;
    else if (c === "/" && !inClass) return i + 1;
    i++;
  }
  return -1;
}
/** End index of the string literal that starts at `start`. */
function endOfString(source: string, start: number): number {
  const quote = source[start];
  let i = start + 1;
  while (i < source.length) {
    if (source[i] === "\\") {
      i += 2;
      continue;
    }
    if (source[i] === quote) return i + 1;
    i++;
  }
  return source.length;
}

/** Index just past the `*\/` that closes the block comment opening at `start`. */
function endOfBlockComment(source: string, start: number): number {
  const close = source.indexOf("*/", start + 2);
  return close === -1 ? source.length : close + 2;
}

/**
 * Source with its comments removed.
 *
 * WITHOUT THIS THE FENCE PUNISHES THE DOCUMENTATION, which is a mistake this
 * repo has made before and wrote down: a scan over raw source flags the comment
 * that explains why a symbol is NOT used. On its first run this fence named
 * five offenders and two of them were prose — `CabaInset.test.tsx` and
 * `StaticFirstMap.tsx` each describe the dynamic-import idiom in a header
 * comment. Telling somebody to fix a sentence is how a fence teaches people to
 * delete their comments.
 *
 * String-aware, so a `https://` inside a literal does not eat the rest of the
 * line — that would be a FALSE NEGATIVE, the direction a fence may never fail
 * in.
 */
export function stripComments(source: string): string {
  const out: string[] = [];
  let i = 0;
  while (i < source.length) {
    const ch = source[i];
    const next = source[i + 1];
    if (ch === "/" && next === "*") {
      i = endOfBlockComment(source, i);
    } else if (ch === "/" && next === "/") {
      while (i < source.length && source[i] !== "\n") i++;
      out.push("\n");
    } else if (ch === '"' || ch === "'" || ch === "`") {
      const end = endOfString(source, i);
      out.push(source.slice(i, end));
      i = end;
    } else if (ch === "/" && REGEX_MAY_FOLLOW.has(lastSignificant(out))) {
      // Checked AFTER the two comment shapes on purpose: `a = /* c */ b` would
      // otherwise read as a regex opening at `/`, and the block comment would
      // never close.
      const end = endOfRegex(source, i);
      if (end === -1) {
        out.push(ch);
        i++;
      } else {
        out.push(source.slice(i, end));
        i = end;
      }
    } else {
      out.push(ch ?? "");
      i++;
    }
  }
  return out.join("");
}

// --- 1. every runtime load goes through the one door ----------------------
//
// `import type` is erased at compile time and cannot reach setWorkerUrl's
// ordering problem, so only VALUE imports count. The loader is the one
// legitimate site.
// `packages` is in the list because the sibling fence check-maplibre-locale.ts
// already scans it; two fences over the same subject disagreeing about
// territory is how a gap opens with nobody noticing it is a gap.
const sources = globSync("{app,components,lib,packages,src}/**/*.{ts,tsx}", {
  exclude: (p) => p.includes("node_modules"),
});
const scanned = sources
  .map((f) => f.replaceAll("\\", "/"))
  .filter((f) => f !== LOADER)
  .map((f) => ({ file: f, code: stripComments(readFileSync(f, "utf8")) }));

const offenders = scanned.filter(({ code }) => loadsMapLibre(code)).map(({ file }) => file);

// The second net: builds a map without coming through the door.
const constructorBypass = scanned
  .filter(({ code }) => MAP_CONSTRUCTOR.test(code) && !code.includes("loadMapLibre"))
  .map(({ file }) => file);
if (constructorBypass.length > 0) {
  problems.push(
    [
      `${constructorBypass.length} file(s) construct a maplibre Map/Marker without importing the loader:`,
      ...constructorBypass.map((f) => `    ${f}`),
      "  However the module reference is spelled, a map built without `loadMapLibre()` may be",
      "  built before `setWorkerUrl` has run. Whether it draws then depends on whether some",
      "  OTHER component on the same page happened to load first — a blank map on one route",
      "  and a working one on the next, with an empty console either way.",
    ].join("\n"),
  );
}

if (offenders.length > 0) {
  problems.push(
    [
      `${offenders.length} file(s) import maplibre-gl at runtime without going through ${LOADER}:`,
      ...offenders.map((f) => `    ${f}`),
      "  `setWorkerUrl` must run before the first `new Map()`, and that ordering is only",
      "  enforceable from one door. A map built from a bypassing import registers its layers,",
      "  fetches nothing, and draws an empty canvas with no console output.",
      "  Use `loadMapLibre()`. `import type` is fine and is not what this matched.",
    ].join("\n"),
  );
}

// Non-vacuity: if the scan cannot see the loader's own import, the regex died
// and every reassuring line above judged nothing.
const loaderText = readFileSync(LOADER, "utf8");
if (!loadsMapLibre(stripComments(loaderText))) {
  problems.push(
    `the scan found no runtime import even in ${LOADER} itself — the detection regex is dead, so the check above judged nothing.`,
  );
}

// --- 2. the build still regenerates the files -----------------------------
const pkg = JSON.parse(readFileSync("package.json", "utf8")) as {
  scripts?: Record<string, string>;
};
for (const hook of ["prebuild", "predev"]) {
  if (!pkg.scripts?.[hook]?.includes("copy-maplibre-worker")) {
    problems.push(
      `package.json has no \`${hook}\` running ${COPY_SCRIPT}. \`${MAPLIBRE_PUBLIC_DIR}\` is gitignored on purpose, so without this hook the worker is simply absent in every fresh checkout and every map is blank.`,
    );
  }
}

// --- 3. the served URL and the copy destination agree ---------------------
const servedRoot = MAPLIBRE_PUBLIC_DIR.replaceAll("\\", "/").replace(/^public\//, "");
const expectedUrl = `/${servedRoot}/${MAPLIBRE_WORKER_ASSETS[0]}`;
const declared = loaderText.match(/MAPLIBRE_WORKER_URL\s*=\s*["']([^"']+)["']/)?.[1];
if (declared !== expectedUrl) {
  problems.push(
    `${LOADER} serves the worker from "${declared}" but ${COPY_SCRIPT} copies it to "${expectedUrl}". One of the two moved, and what the browser gets is a 200 carrying the app's HTML.`,
  );
}

// --- 4. the installed worker still needs exactly what we copy -------------
const dist = maplibreDistDir();
const version = maplibreVersion();
// AN ENUMERATION, NOT AN INCLUSION TEST, and the difference is a whole class of
// silent failure. Asserting the known file is still imported fires when it goes
// AWAY; it cannot fire when an UNKNOWN one is added. A future 6.11 that keeps
// ./maplibre-gl-shared.mjs and adds ./maplibre-gl-util.mjs would pass that
// check, ship two of three files, and every map would go blank again — green
// build, green fence, empty console.
const unexpected = unknownRelativeImports(dist);
if (unexpected.length > 0) {
  problems.push(
    `maplibre-gl ${version}: the copied files import relative modules this script does not copy: ${unexpected.join(", ")}. Shipping them without those would produce a worker that cannot load — silently, the way it already did once. Add them to MAPLIBRE_WORKER_ASSETS.`,
  );
}

// --- 5. if the copies exist, they are the installed ones ------------------
let compared = 0;
if (existsSync(MAPLIBRE_PUBLIC_DIR)) {
  for (const name of MAPLIBRE_WORKER_ASSETS) {
    const served = join(MAPLIBRE_PUBLIC_DIR, name);
    if (!existsSync(served)) {
      problems.push(`${MAPLIBRE_PUBLIC_DIR}/${name} is missing — run \`tsx ${COPY_SCRIPT}\`.`);
      continue;
    }
    if (sha(served) !== sha(join(dist, name))) {
      problems.push(
        `${MAPLIBRE_PUBLIC_DIR}/${name} is not the installed maplibre-gl ${version}. A stale worker fails the same silent way a missing one does.`,
      );
    }
    compared++;
  }
}

if (problems.length > 0) {
  console.error(`\n✗ maplibre worker wiring FAILED\n\n${problems.join("\n\n")}\n`);
  process.exit(1);
}

const copiesNote = compared === 0 ? " (none on disk yet — generated at build)" : "";
console.log(
  `✓ maplibre worker wiring clean — maplibre-gl ${version}; ${sources.length} source file(s) scanned, every runtime load goes through ${LOADER}; prebuild/predev regenerate ${MAPLIBRE_WORKER_ASSETS.length} asset(s); ${compared} served copy/copies checked against node_modules${copiesNote}.`,
);
