/**
 * Original 10 storylines — rewritten under the new rules.
 *
 * Relocated entirely to CABA Comunas 1 (Retiro / Puerto Madero / San Nicolás),
 * 2 (Recoleta), 14 (Palermo). Microchips only where realistic. No resurrection;
 * Brian dies and Vinny is registered as the canon-friend replacement to Noelí.
 *
 * Owner pinning:
 *   Ignacio  — Scooby, Snoopy, Tom (deceased), Bolt, Puss (deceased), Odie
 *   Noelí    — Santa's Little Helper, Brian (deceased), Vinny
 *   Graciela — Blue, Courage
 *
 * Closed cycles (deceased, no replacement except where noted):
 *   Scooby-Doo  — old age 2025, cremation_individual_ashes
 *   Tom         — CKD terminal 2024, owner_burial
 *   Brian       — traffic accident 2023, cremation_individual_ashes → Vinny replacement
 *   Puss        — final fall 2025, owner_burial
 *
 * Authored by the appropriate seed user via author_role:
 *   vet events → Lilian, govt events → Lucas, shelter → Alejo, system → null,
 *   everything else → the pet's owner.
 */

import type { Storyline } from "./seed-storylines-iconic";

const CABA = (locality: string, landmark?: string) => ({
  locality,
  province: "CABA",
  ...(landmark ? { landmark } : {}),
});

// ---------------------------------------------------------------------------
// 1. Scooby-Doo — Great Dane, Palermo (Ignacio), deceased 2025
// ---------------------------------------------------------------------------

const scooby: Storyline = {
  pet: {
    display_name: "Scooby-Doo",
    public_token: "DIM-SCDO-0001",
    species: "dog",
    breed: "Gran Danés",
    sex: "male",
    date_of_birth: "2012-04-12",
    color: "Marrón con manchas negras",
    microchip_id: "858112345678901",
    microchip_country_code: "858",
    microchip_implanted_at: "2012-08-10",
    microchip_implanted_by: "Clínica Veterinaria Recoleta",
    microchip_location: "interscapular_left",
    estimated_weight_kg: 38,
    known_allergies: ["mariscos"],
    potentially_dangerous_breed: false,
    jurisdiction_country: "AR",
    jurisdiction_province: "CABA",
    jurisdiction_locality: "Palermo",
    acquisition_method: "adopted",
    emergency_info_visible: true,
    status: "deceased",
    owner: "ignacio",
    photo_file: "scobi.webp",
    notes: "Canonical handler: Norville 'Shaggy' Rogers. Curatorial owner: Ignacio.",
  },
  events: [
    {
      date: "2012-04-12",
      event_type: "pet_registered",
      author_role: "owner",
      location: CABA("Palermo"),
      payload: { acquisition_method: "adopted" },
    },
    {
      date: "2012-06-20",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "intake_exam" },
    },
    {
      date: "2012-07-15",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP #1" },
    },
    {
      date: "2012-08-10",
      event_type: "microchip_implanted",
      author_role: "vet",
      payload: {
        chip_number: "858112345678901",
        country_code: "858",
        implanted_by: "Clínica Veterinaria Recoleta",
        location_on_body: "interscapular_left",
        implant_date_known: true,
      },
    },
    {
      date: "2012-08-25",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP #2 + antirrábica" },
    },
    {
      date: "2013-01-20",
      event_type: "vet_visit_logged",
      author_role: "vet",
      location: CABA("Palermo"),
      payload: { reason: "gastroenteritis", diagnosis: "ingestión de 1.4kg de galletitas" },
      uncommon: true,
    },
    { date: "2013-03-15", event_type: "weight_recorded", author_role: "vet", payload: { kg: 38 } },
    {
      date: "2014-02-10",
      event_type: "pet_profile_updated",
      author_role: "owner",
      payload: { changes: [{ field: "photo", old: "old", new: "perfil-2014" }] },
    },
    {
      date: "2014-05-18",
      event_type: "status_changed",
      author_role: "owner",
      location: CABA("Palermo", "Bosques de Palermo"),
      payload: {
        from_status: "active",
        to_status: "lost",
        location_description: "Bosques de Palermo — separado en parrillada",
      },
      uncommon: true,
    },
    {
      date: "2014-05-19",
      event_type: "credential_scanned",
      author_role: "system",
      location: CABA("Palermo"),
      payload: {
        is_self_scan: false,
        viewer_authenticated: false,
        viewer_name: "Fred Jones (vecino)",
      },
    },
    {
      date: "2014-05-19",
      event_type: "status_changed",
      author_role: "owner",
      payload: { from_status: "lost", to_status: "active" },
    },
    {
      date: "2014-07-12",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual" },
    },
    {
      date: "2015-04-20",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "fluoxetina",
        dose: "20 mg",
        frequency: "SID",
        first_dose_at: "2015-04-20",
        schedule_count: 365,
      },
      uncommon: true,
    },
    {
      date: "2015-09-12",
      event_type: "credential_scanned",
      author_role: "system",
      payload: { is_self_scan: true, viewer_authenticated: true },
    },
    {
      date: "2016-01-15",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: {
        sub_kind: "surgery",
        title: "Laparotomía exploratoria — cuerpo extraño retirado (llave de bronce)",
      },
      uncommon: true,
    },
    {
      date: "2016-04-04",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "other", title: "Profilaxis dental + 2 extracciones" },
    },
    { date: "2017-05-30", event_type: "weight_recorded", author_role: "vet", payload: { kg: 41 } },
    {
      date: "2018-03-20",
      event_type: "incident_reported",
      author_role: "owner",
      location: CABA("Palermo", "Plaza Italia"),
      payload: {
        incident_type: "bite_inflicted",
        severity: "leve",
        injuries_summary: "Mordedura de provocación (sin lesión cutánea) a actor disfrazado",
      },
      uncommon: true,
    },
    {
      date: "2018-12-05",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: {
        sub_kind: "allergy_detection",
        title: "Anafilaxia por mariscos — receta epinefrina autoinyectable",
      },
      uncommon: true,
    },
    {
      date: "2019-11-02",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "imaging", title: "Rx caderas — displasia bilateral leve" },
    },
    {
      date: "2019-11-10",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "meloxicam",
        dose: "0.1 mg/kg",
        frequency: "SID",
        first_dose_at: "2019-11-10",
        schedule_count: 365,
      },
    },
    {
      date: "2020-12-25",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "ingestión chocolate amargo 200g", diagnosis: "intoxicación leve" },
      uncommon: true,
    },
    {
      date: "2021-08-08",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "surgery", title: "Excisión lipoma hombro derecho" },
    },
    {
      date: "2022-01-19",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "lab_work", title: "Panel senior — BUN/creatinina limítrofe" },
    },
    {
      date: "2023-09-17",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual senior" },
    },
    {
      date: "2024-04-30",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "imaging", title: "Eco cardíaca — soplo II/VI funcional" },
    },
    {
      date: "2025-03-04",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "úlcera corneal OD" },
    },
    { date: "2025-11-11", event_type: "weight_recorded", author_role: "vet", payload: { kg: 36 } },
    {
      date: "2025-12-22",
      event_type: "symptom_observed",
      author_role: "vet",
      payload: {
        source: "libreta",
        reporter_role: "vet",
        free_text: "deterioro cognitivo + caquexia geriátrica",
        matched_symptom_codes: ["cognitive_decline", "cachexia"],
        alerted_disease_codes: [],
      },
      uncommon: true,
    },
    {
      date: "2025-12-28",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "quality_of_life_check" },
    },
    {
      date: "2025-12-30",
      event_type: "death_recorded",
      author_role: "vet",
      location: CABA("Palermo"),
      payload: {
        cause: "euthanasia",
        cause_detail: "calidad de vida — disfunción cognitiva avanzada + sarcopenia",
        confirmed_by_vet: true,
        vet_name: "Dra. Lilian Marrone",
        disposition_method: "cremation_individual_ashes",
        facility: "Crematorio Mascotas Norte, Tigre",
        death_at_clinic: true,
        vet_contacted_owner: "yes",
        vet_decided_alone: false,
        is_reportable: false,
      },
      uncommon: true,
    },
    {
      date: "2025-12-31",
      event_type: "note_added",
      author_role: "owner",
      payload: {
        category: "despedida",
        text: "Scooby — gracias por todas las galletitas y todos los sustos que enfrentaste con la boca llena. Te queremos. — Ignacio",
      },
      uncommon: true,
    },
  ],
};

// ---------------------------------------------------------------------------
// 2. Santa's Little Helper — Greyhound, Recoleta (Noelí), active
// ---------------------------------------------------------------------------

const slh: Storyline = {
  pet: {
    display_name: "Santa's Little Helper",
    public_token: "DIM-SLHP-0003",
    species: "dog",
    breed: "Galgo (Greyhound)",
    sex: "male",
    date_of_birth: "2017-05-01",
    color: "Brindle",
    microchip_id: "858088100200300",
    microchip_country_code: "858",
    microchip_implanted_at: "2018-02-08",
    microchip_implanted_by: "Refugio Patitas del Norte",
    microchip_location: "interscapular_left",
    estimated_weight_kg: 28,
    potentially_dangerous_breed: false,
    jurisdiction_country: "AR",
    jurisdiction_province: "CABA",
    jurisdiction_locality: "Recoleta",
    acquisition_method: "rescued",
    status: "active",
    owner: "noeli",
    photo_file: "shl2.jpg",
    notes:
      "Ex-galgo de carrera adoptado el 24-dic de un canódromo clausurado. Canonical handler: Familia Simpson.",
  },
  events: [
    {
      date: "2017-12-24",
      event_type: "shelter_intake_recorded",
      author_role: "shelter",
      payload: { intake_reason: "stray_found", intake_condition: "underweight" },
      uncommon: true,
    },
    {
      date: "2017-12-24",
      event_type: "pet_registered",
      author_role: "owner",
      payload: { acquisition_method: "rescued" },
    },
    {
      date: "2017-12-26",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "intake_exam", body_condition_score: 2 },
    },
    {
      date: "2018-01-14",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP catch-up + antirrábica" },
    },
    {
      date: "2018-02-08",
      event_type: "microchip_implanted",
      author_role: "vet",
      payload: {
        chip_number: "858088100200300",
        country_code: "858",
        implanted_by: "Refugio Patitas del Norte",
        location_on_body: "interscapular_left",
        implant_date_known: true,
      },
    },
    {
      date: "2018-04-22",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: {
        sub_kind: "surgery",
        title: "Gastropexia preventiva + esplenectomía por GDV agudo",
      },
      uncommon: true,
    },
    {
      date: "2019-04-22",
      event_type: "sterilization_performed",
      author_role: "vet",
      payload: {
        procedure: "castration",
        performed_by: "Dra. Lilian Marrone",
        clinic: "Clínica Veterinaria Recoleta",
      },
    },
    {
      date: "2019-10-30",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual" },
    },
    {
      date: "2020-06-18",
      event_type: "status_changed",
      author_role: "owner",
      location: CABA("Recoleta", "Plaza Vicente López"),
      payload: { from_status: "active", to_status: "lost" },
      uncommon: true,
    },
    {
      date: "2020-06-19",
      event_type: "credential_scanned",
      author_role: "system",
      location: CABA("Recoleta"),
      payload: {
        is_self_scan: false,
        viewer_authenticated: false,
        viewer_name: "Apu Nahasapeemapetilon (almacenero, Av. Las Heras)",
      },
    },
    {
      date: "2020-06-19",
      event_type: "status_changed",
      author_role: "owner",
      payload: { from_status: "lost", to_status: "active" },
    },
    {
      date: "2020-10-15",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "fall",
        severity: "leve",
        injuries_summary: "Tropezón en escalera; sin fracturas",
      },
    },
    {
      date: "2021-04-22",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual" },
    },
    {
      date: "2022-05-15",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "lab_work", title: "Panel anual — TSH bajo" },
    },
    {
      date: "2022-05-22",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "levotiroxina",
        dose: "0.4 mg",
        frequency: "BID",
        first_dose_at: "2022-05-22",
        schedule_count: 730,
      },
    },
    { date: "2023-09-09", event_type: "weight_recorded", author_role: "vet", payload: { kg: 28 } },
    {
      date: "2024-04-22",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual senior" },
    },
    {
      date: "2025-02-14",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "imaging", title: "Rx tórax — sin lesiones" },
    },
    {
      date: "2026-03-15",
      event_type: "weight_recorded",
      author_role: "vet",
      payload: { kg: 28.5 },
    },
    {
      date: "2026-04-22",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual senior", next_due_at: "2027-04-22" },
    },
    {
      date: "2026-05-10",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "wellness" },
    },
  ],
};

// ---------------------------------------------------------------------------
// 3. Snoopy — Beagle, Puerto Madero (Ignacio), active
// ---------------------------------------------------------------------------

const snoopy: Storyline = {
  pet: {
    display_name: "Snoopy",
    public_token: "DIM-SNPY-0004",
    species: "dog",
    breed: "Beagle",
    sex: "male",
    date_of_birth: "2016-08-10",
    color: "Blanco y negro",
    microchip_id: "858200100555100",
    microchip_country_code: "858",
    microchip_implanted_at: "2019-04-15",
    microchip_implanted_by: "Refugio Patitas del Norte",
    microchip_location: "interscapular_left",
    estimated_weight_kg: 11,
    potentially_dangerous_breed: false,
    jurisdiction_country: "AR",
    jurisdiction_province: "CABA",
    jurisdiction_locality: "Puerto Madero",
    acquisition_method: "adopted",
    status: "active",
    owner: "ignacio",
    photo_file: "snoppy 3.jpg",
    notes:
      "Adoptado tras pasar por dos casas. Canonical handler: Charlie Brown. Chip implantado tarde tras múltiples episodios de extravío.",
  },
  events: [
    {
      date: "2016-08-10",
      event_type: "pet_registered",
      author_role: "owner",
      payload: { acquisition_method: "purchased" },
    },
    {
      date: "2016-10-22",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP #1" },
    },
    {
      date: "2017-02-03",
      event_type: "custody_transferred",
      author_role: "owner",
      payload: {
        from_user_id: "Lila",
        to_user_id: "Charlie Brown",
        from_role: "owner",
        to_role: "owner",
        reason: "edificio no admite mascotas",
      },
      uncommon: true,
    },
    {
      date: "2017-02-08",
      event_type: "pet_profile_updated",
      author_role: "owner",
      payload: { changes: [{ field: "owner", old: "Lila", new: "Ignacio (curatorial)" }] },
    },
    {
      date: "2017-03-12",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "wellness post-rehome" },
    },
    {
      date: "2017-04-04",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP #2 + antirrábica" },
    },
    {
      date: "2018-01-20",
      event_type: "status_changed",
      author_role: "owner",
      location: CABA("Puerto Madero", "Dique 3"),
      payload: { from_status: "active", to_status: "lost" },
      uncommon: true,
    },
    {
      date: "2018-01-22",
      event_type: "credential_scanned",
      author_role: "system",
      payload: {
        is_self_scan: false,
        viewer_authenticated: false,
        viewer_name: "Linus Van Pelt (vecino, Puerto Madero)",
      },
    },
    {
      date: "2018-01-22",
      event_type: "status_changed",
      author_role: "owner",
      payload: { from_status: "lost", to_status: "active" },
    },
    {
      date: "2019-04-15",
      event_type: "microchip_implanted",
      author_role: "vet",
      payload: {
        chip_number: "858200100555100",
        country_code: "858",
        implanted_by: "Refugio Patitas del Norte",
        location_on_body: "interscapular_left",
        implant_date_known: true,
        note: "implantado tras tercer extravío",
      },
      uncommon: true,
    },
    {
      date: "2019-12-12",
      event_type: "foster_proposed",
      author_role: "shelter",
      payload: { foster_user_id: "Linus", expected_weeks: 2, reason: "owner viaja" },
      uncommon: true,
    },
    {
      date: "2019-12-13",
      event_type: "foster_proposal_resolved",
      author_role: "shelter",
      payload: { proposal_public_token: "prop-snoopy-2019-12-12", outcome: "accepted" },
    },
    {
      date: "2019-12-13",
      event_type: "foster_assigned",
      author_role: "shelter",
      payload: { foster_user_id: "Linus", expected_weeks: 2 },
    },
    {
      date: "2019-12-27",
      event_type: "foster_ended",
      author_role: "shelter",
      payload: { ended_by: "shelter", reason: "owner regresó" },
    },
    {
      date: "2020-08-15",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "escape",
        severity: "leve",
        injuries_summary: "Salida no autorizada por puerta del balcón",
      },
      uncommon: true,
    },
    {
      date: "2021-01-04",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "esguince corvejón derecho" },
    },
    {
      date: "2022-07-09",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "SAMe + UDCA",
        dose: "200 mg",
        frequency: "SID",
        first_dose_at: "2022-07-09",
        schedule_count: 90,
      },
    },
    {
      date: "2024-12-25",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "wellness" },
    },
    {
      date: "2025-08-10",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "9th birthday senior wellness" },
    },
    {
      date: "2026-02-14",
      event_type: "weight_recorded",
      author_role: "vet",
      payload: { kg: 11.2 },
    },
    {
      date: "2026-04-20",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual senior", next_due_at: "2027-04-20" },
    },
    {
      date: "2026-05-12",
      event_type: "credential_scanned",
      author_role: "system",
      payload: { is_self_scan: true, viewer_authenticated: true },
    },
  ],
};

// ---------------------------------------------------------------------------
// 4. Tom — DSH cat, Retiro (Ignacio), deceased 2024 (CKD)
// ---------------------------------------------------------------------------

const tom: Storyline = {
  pet: {
    display_name: "Tom",
    public_token: "DIM-TOMC-0008",
    species: "cat",
    breed: "Común europeo",
    sex: "male",
    date_of_birth: "2009-08-12",
    color: "Gris azulado y blanco",
    microchip_id: "858500700700700",
    microchip_country_code: "858",
    microchip_implanted_at: "2009-12-04",
    microchip_implanted_by: "Refugio Patitas del Norte",
    microchip_location: "interscapular_left",
    estimated_weight_kg: 5.0,
    potentially_dangerous_breed: false,
    jurisdiction_country: "AR",
    jurisdiction_province: "CABA",
    jurisdiction_locality: "Retiro",
    acquisition_method: "rescued",
    status: "deceased",
    owner: "ignacio",
    photo_file: "tom.jpg",
    notes: "Chip reemplazado en 2017 tras duplicado detectado. Final cycle: ERC.",
  },
  events: [
    {
      date: "2009-10-15",
      event_type: "shelter_intake_recorded",
      author_role: "shelter",
      payload: { intake_reason: "stray_found", intake_condition: "healthy" },
    },
    {
      date: "2009-11-01",
      event_type: "pet_registered",
      author_role: "owner",
      payload: { acquisition_method: "adopted" },
    },
    {
      date: "2009-11-15",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "FVRCP + antirrábica" },
    },
    {
      date: "2009-12-04",
      event_type: "microchip_implanted",
      author_role: "vet",
      payload: {
        chip_number: "858500700700700",
        country_code: "858",
        implanted_by: "Refugio Patitas del Norte",
        location_on_body: "interscapular_left",
        implant_date_known: true,
      },
    },
    {
      date: "2010-03-22",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "trauma cefálico — golpe doméstico" },
    },
    {
      date: "2010-09-09",
      event_type: "sterilization_performed",
      author_role: "vet",
      payload: { procedure: "castration", performed_by: "Dra. Lilian Marrone" },
    },
    {
      date: "2014-09-30",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "other", title: "Profilaxis dental + 2 extracciones" },
    },
    {
      date: "2017-03-22",
      event_type: "microchip_replaced",
      author_role: "system",
      payload: {
        previous_chip_number: "858500700700700",
        new_chip_number: "858500700700701",
        reason: "duplicate_detected",
      },
      uncommon: true,
    },
    { date: "2018-08-08", event_type: "weight_recorded", author_role: "vet", payload: { kg: 5.5 } },
    {
      date: "2019-04-04",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "lesión menor — quemadura eléctrica leve" },
    },
    {
      date: "2022-09-09",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "other", title: "Profilaxis dental anual" },
    },
    {
      date: "2023-04-22",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "lab_work", title: "Senior panel — ERC estadio II" },
      uncommon: true,
    },
    {
      date: "2023-09-15",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "dieta renal + benazepril",
        dose: "0.5 mg/kg",
        frequency: "SID",
        first_dose_at: "2023-09-15",
        schedule_count: 365,
      },
    },
    {
      date: "2024-03-30",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "FVRCP senior" },
    },
    {
      date: "2024-11-11",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "lab_work", title: "ERC estadio III; subQ fluids" },
      uncommon: true,
    },
    {
      date: "2024-12-08",
      event_type: "symptom_observed",
      author_role: "owner",
      payload: {
        source: "libreta",
        reporter_role: "owner",
        free_text: "Anorexia + decaimiento severo",
        matched_symptom_codes: ["anorexia", "lethargy"],
        alerted_disease_codes: ["renal_failure"],
      },
      uncommon: true,
    },
    {
      date: "2024-12-10",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "quality_of_life_check" },
    },
    {
      date: "2024-12-15",
      event_type: "medication_stopped",
      author_role: "vet",
      payload: { reason: "QoL — paliativo" },
    },
    {
      date: "2024-12-22",
      event_type: "death_recorded",
      author_role: "vet",
      location: CABA("Retiro"),
      payload: {
        cause: "disease",
        cause_detail: "ERC terminal estadio IV",
        confirmed_by_vet: true,
        vet_name: "Dra. Lilian Marrone",
        disposition_method: "owner_burial",
        facility: "Domicilio Ignacio del Valle, Retiro",
        death_at_clinic: false,
        vet_contacted_owner: "yes",
        is_reportable: false,
      },
      uncommon: true,
    },
    {
      date: "2024-12-23",
      event_type: "note_added",
      author_role: "owner",
      payload: {
        category: "despedida",
        text: "Tom — los pianos te debieron a vos toda una carrera. Buen viaje. — Ignacio",
      },
      uncommon: true,
    },
  ],
};

// ---------------------------------------------------------------------------
// 5. Blue — Blue Heeler, Palermo (Graciela), active, 3-handler chain
// ---------------------------------------------------------------------------

const blue: Storyline = {
  pet: {
    display_name: "Blue",
    public_token: "DIM-BLUE-0010",
    species: "dog",
    breed: "Pastor Australiano (Blue Heeler)",
    sex: "female",
    date_of_birth: "2014-09-08",
    color: "Azul moteado",
    microchip_id: "858600101202303",
    microchip_country_code: "858",
    microchip_implanted_at: "2014-11-20",
    microchip_implanted_by: "Clínica Veterinaria Recoleta",
    microchip_location: "interscapular_left",
    estimated_weight_kg: 16,
    potentially_dangerous_breed: false,
    jurisdiction_country: "AR",
    jurisdiction_province: "CABA",
    jurisdiction_locality: "Palermo",
    acquisition_method: "adopted",
    status: "active",
    owner: "graciela",
    photo_file: "bluee.jpg",
    notes: "Tres handlers a lo largo del registro (Steve → Joe → Josh). Curatorial owner Graciela.",
  },
  events: [
    {
      date: "2014-11-15",
      event_type: "pet_registered",
      author_role: "owner",
      payload: { acquisition_method: "adopted" },
    },
    {
      date: "2014-11-20",
      event_type: "microchip_implanted",
      author_role: "vet",
      payload: {
        chip_number: "858600101202303",
        country_code: "858",
        implanted_by: "Clínica Veterinaria Recoleta",
        location_on_body: "interscapular_left",
        implant_date_known: true,
      },
    },
    {
      date: "2014-12-01",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP" },
    },
    {
      date: "2015-06-30",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP #2 + antirrábica" },
    },
    {
      date: "2017-05-30",
      event_type: "custody_transfer_proposed",
      author_role: "owner",
      payload: { from_user_id: "Steve", to_user_id: "Joe", reason: "handler transition" },
      uncommon: true,
    },
    {
      date: "2017-06-15",
      event_type: "custody_transferred",
      author_role: "owner",
      payload: { from_user_id: "Steve", to_user_id: "Joe", from_role: "owner", to_role: "owner" },
    },
    {
      date: "2018-02-22",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual" },
    },
    {
      date: "2020-06-09",
      event_type: "status_changed",
      author_role: "owner",
      location: CABA("Palermo", "Plaza Italia"),
      payload: { from_status: "active", to_status: "lost" },
    },
    {
      date: "2020-06-09",
      event_type: "credential_scanned",
      author_role: "system",
      payload: { is_self_scan: false, viewer_authenticated: false, viewer_name: "vecino Magenta" },
    },
    {
      date: "2020-06-09",
      event_type: "status_changed",
      author_role: "owner",
      payload: { from_status: "lost", to_status: "active" },
    },
    {
      date: "2021-11-09",
      event_type: "custody_transfer_proposed",
      author_role: "owner",
      payload: { from_user_id: "Joe", to_user_id: "Josh", reason: "second handler transition" },
      uncommon: true,
    },
    {
      date: "2021-11-15",
      event_type: "custody_transferred",
      author_role: "owner",
      payload: { from_user_id: "Joe", to_user_id: "Josh", from_role: "owner", to_role: "owner" },
    },
    {
      date: "2022-03-15",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual" },
    },
    {
      date: "2023-06-22",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "other", title: "Profilaxis dental + 1 extracción" },
    },
    { date: "2024-04-22", event_type: "weight_recorded", author_role: "vet", payload: { kg: 16 } },
    {
      date: "2024-12-04",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "glucosamina + omega-3",
        dose: "500 mg",
        frequency: "SID",
        first_dose_at: "2024-12-04",
        schedule_count: 365,
      },
    },
    {
      date: "2025-11-25",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "imaging", title: "Rx caderas — OA leve incipiente" },
    },
    {
      date: "2026-02-14",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "12th-year wellness" },
    },
    {
      date: "2026-05-05",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual senior", next_due_at: "2027-05-05" },
    },
    {
      date: "2026-05-10",
      event_type: "note_added",
      author_role: "owner",
      payload: { category: "rutina", text: "Blue sigue resolviendo las pistas del jardín." },
    },
  ],
};

// ---------------------------------------------------------------------------
// 6. Bolt — White Swiss Shepherd, Recoleta (Ignacio), active
// ---------------------------------------------------------------------------

const bolt: Storyline = {
  pet: {
    display_name: "Bolt",
    public_token: "DIM-BOLT-0006",
    species: "dog",
    breed: "Pastor Suizo Blanco",
    sex: "male",
    date_of_birth: "2015-09-01",
    color: "Blanco",
    microchip_id: "858400555666777",
    microchip_country_code: "858",
    microchip_implanted_at: "2015-11-16",
    microchip_implanted_by: "Clínica Veterinaria Recoleta",
    microchip_location: "interscapular_left",
    estimated_weight_kg: 26,
    potentially_dangerous_breed: false,
    jurisdiction_country: "AR",
    jurisdiction_province: "CABA",
    jurisdiction_locality: "Recoleta",
    acquisition_method: "adopted",
    status: "active",
    owner: "ignacio",
    photo_file: "bolt.jpg",
    notes: "Episodio de extravío con scan-burst cross-CABA. Curatorial owner: Ignacio.",
  },
  events: [
    {
      date: "2015-09-01",
      event_type: "pet_registered",
      author_role: "owner",
      payload: { acquisition_method: "adopted" },
    },
    {
      date: "2015-10-30",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP #1" },
    },
    {
      date: "2015-11-16",
      event_type: "microchip_implanted",
      author_role: "vet",
      payload: {
        chip_number: "858400555666777",
        country_code: "858",
        implanted_by: "Clínica Veterinaria Recoleta",
        location_on_body: "interscapular_left",
        implant_date_known: true,
      },
    },
    {
      date: "2015-12-04",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP #2 + antirrábica" },
    },
    {
      date: "2017-09-30",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "quemadura pata derecha" },
    },
    {
      date: "2020-02-14",
      event_type: "status_changed",
      author_role: "owner",
      location: CABA("Recoleta", "Cementerio de la Recoleta"),
      payload: { from_status: "active", to_status: "lost" },
      uncommon: true,
    },
    {
      date: "2020-02-15",
      event_type: "credential_scanned",
      author_role: "system",
      location: CABA("Retiro"),
      payload: {
        is_self_scan: false,
        viewer_authenticated: false,
        viewer_name: "Plaza San Martín scan #1",
      },
      uncommon: true,
    },
    {
      date: "2020-02-15",
      event_type: "credential_scanned",
      author_role: "system",
      location: CABA("San Nicolás"),
      payload: {
        is_self_scan: false,
        viewer_authenticated: false,
        viewer_name: "Obelisco scan #2",
      },
    },
    {
      date: "2020-02-16",
      event_type: "credential_scanned",
      author_role: "system",
      location: CABA("Puerto Madero"),
      payload: { is_self_scan: false, viewer_authenticated: false, viewer_name: "Dique 1 scan #3" },
    },
    {
      date: "2020-02-16",
      event_type: "credential_scanned",
      author_role: "system",
      location: CABA("Palermo"),
      payload: { is_self_scan: false, viewer_authenticated: false, viewer_name: "Bosques scan #4" },
    },
    {
      date: "2020-02-17",
      event_type: "credential_scanned",
      author_role: "system",
      location: CABA("Recoleta"),
      payload: {
        is_self_scan: false,
        viewer_authenticated: false,
        viewer_name: "Plaza Vicente López scan #5 (Mittens)",
      },
      uncommon: true,
    },
    {
      date: "2020-02-17",
      event_type: "status_changed",
      author_role: "owner",
      payload: { from_status: "lost", to_status: "active" },
    },
    {
      date: "2020-04-05",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "lab_work", title: "Heartworm antigeno positivo — D. immitis" },
      uncommon: true,
    },
    {
      date: "2020-04-12",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "melarsomina (protocolo 3 inyecciones AHS)",
        dose: "2.5 mg/kg",
        frequency: "protocolo",
        first_dose_at: "2020-04-12",
        schedule_count: 3,
      },
    },
    {
      date: "2020-08-15",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "lab_work", title: "Heartworm antigeno negativo — tratamiento exitoso" },
      uncommon: true,
    },
    {
      date: "2022-08-22",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "esguince hombro" },
    },
    {
      date: "2024-03-15",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "imaging", title: "Rx caderas — OA leve" },
    },
    {
      date: "2024-08-08",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "carprofeno",
        dose: "2 mg/kg",
        frequency: "BID",
        first_dose_at: "2024-08-08",
        schedule_count: 365,
      },
    },
    {
      date: "2025-10-10",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual" },
    },
    {
      date: "2026-04-30",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "11th-year senior assessment" },
    },
    {
      date: "2026-05-15",
      event_type: "weight_recorded",
      author_role: "vet",
      payload: { kg: 26.5 },
    },
  ],
};

// ---------------------------------------------------------------------------
// 7. Brian Griffin — Labrador-mix, Palermo (Noelí), DECEASED 2023 (vehicular)
// ---------------------------------------------------------------------------

const brian: Storyline = {
  pet: {
    display_name: "Brian Griffin",
    public_token: "DIM-BRGR-0002",
    species: "dog",
    breed: "Mestizo Labrador",
    sex: "male",
    date_of_birth: "2010-07-04",
    color: "Blanco",
    estimated_weight_kg: 25,
    potentially_dangerous_breed: false,
    jurisdiction_country: "AR",
    jurisdiction_province: "CABA",
    jurisdiction_locality: "Palermo",
    acquisition_method: "rescued",
    status: "deceased",
    owner: "noeli",
    photo_file: "brian 1.jpg",
    notes:
      "Sin microchip — encontrado en la calle, registrado de manera informal. Muere atropellado sobre Av. 9 de Julio (2023). NO RESURRECTION. Reemplazado por Vinny (canon-friend).",
  },
  events: [
    {
      date: "2010-09-12",
      event_type: "shelter_intake_recorded",
      author_role: "shelter",
      payload: { intake_reason: "stray_found", intake_condition: "underweight" },
      uncommon: true,
    },
    {
      date: "2010-09-13",
      event_type: "pet_registered",
      author_role: "owner",
      payload: { acquisition_method: "rescued" },
    },
    {
      date: "2010-11-20",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP + antirrábica (catch-up)" },
    },
    {
      date: "2011-05-09",
      event_type: "incident_reported",
      author_role: "owner",
      location: CABA("Palermo"),
      payload: {
        incident_type: "other",
        severity: "leve",
        injuries_summary: "Encontrado intoxicado por bebidas alcohólicas en evento privado",
      },
      uncommon: true,
    },
    {
      date: "2012-04-18",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "SSRI (off-label, ansiedad)",
        dose: "20 mg",
        frequency: "SID",
        first_dose_at: "2012-04-18",
        schedule_count: 365,
      },
      uncommon: true,
    },
    {
      date: "2014-08-30",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "wellness anual" },
    },
    {
      date: "2015-10-31",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "bite_inflicted",
        severity: "leve",
        injuries_summary: "Mordedura a ave de neighbor (sin daño humano)",
      },
    },
    {
      date: "2016-04-18",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "trastorno digestivo crónico" },
    },
    {
      date: "2017-03-19",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "imaging", title: "Eco abdominal — hígado graso" },
      uncommon: true,
    },
    {
      date: "2018-08-04",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "pancreatitis recurrente — dieta low-fat indicada" },
    },
    {
      date: "2019-11-05",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "lab_work", title: "Senior — TSH bajo" },
    },
    {
      date: "2020-04-22",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "levotiroxina",
        dose: "0.4 mg",
        frequency: "BID",
        first_dose_at: "2020-04-22",
        schedule_count: 730,
      },
    },
    {
      date: "2021-09-22",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "rehabilitación abuso sustancias — programa ambulatorio" },
      uncommon: true,
    },
    {
      date: "2022-02-14",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual" },
    },
    {
      date: "2023-07-04",
      event_type: "weight_recorded",
      author_role: "vet",
      payload: { kg: 25.8 },
    },
    {
      date: "2023-11-24",
      event_type: "incident_reported",
      author_role: "owner",
      location: CABA("San Nicolás", "Av. 9 de Julio"),
      payload: {
        incident_type: "traffic_accident",
        severity: "fatal",
        injuries_summary: "Atropellado por colectivo línea 5 — DOA en clínica",
      },
      uncommon: true,
    },
    {
      date: "2023-11-24",
      event_type: "death_recorded",
      author_role: "vet",
      location: CABA("San Nicolás"),
      payload: {
        cause: "accident",
        cause_detail:
          "trauma vehicular múltiple — atropellado por colectivo línea 5 sobre Av. 9 de Julio",
        confirmed_by_vet: true,
        vet_name: "Dra. Lilian Marrone",
        disposition_method: "cremation_individual_ashes",
        facility: "Crematorio Mascotas Norte, Tigre",
        death_at_clinic: true,
        vet_contacted_owner: "yes",
        is_reportable: false,
      },
      uncommon: true,
    },
    {
      date: "2023-11-26",
      event_type: "note_added",
      author_role: "owner",
      payload: {
        category: "despedida",
        text: "Brian — escribiste seis novelas inéditas y dijiste muchas cosas que la familia necesitaba escuchar. Nunca volverás. Y eso es lo que duele. — Noelí",
      },
      uncommon: true,
    },
    {
      date: "2023-12-15",
      event_type: "pet_registered",
      author_role: "owner",
      payload: {
        name: "Vinny",
        acquisition_method: "adopted",
        note: "Reemplazo canon-friend (Vincenzo) registrado a misma dueña. Ver DIM-VINY-0002B.",
      },
      uncommon: true,
    },
  ],
};

// ---------------------------------------------------------------------------
// 8. Vinny — Brian's replacement (Italian Spinone), Palermo (Noelí), active
// ---------------------------------------------------------------------------

const vinny: Storyline = {
  pet: {
    display_name: "Vinny",
    public_token: "DIM-VINY-0002B",
    species: "dog",
    breed: "Spinone Italiano",
    sex: "male",
    date_of_birth: "2023-08-10",
    color: "Marrón claro",
    microchip_id: "858200200200200",
    microchip_country_code: "858",
    microchip_implanted_at: "2023-12-20",
    microchip_implanted_by: "Clínica Veterinaria Recoleta",
    microchip_location: "interscapular_left",
    estimated_weight_kg: 22,
    potentially_dangerous_breed: false,
    jurisdiction_country: "AR",
    jurisdiction_province: "CABA",
    jurisdiction_locality: "Palermo",
    acquisition_method: "adopted",
    status: "active",
    owner: "noeli",
    notes:
      "Reemplazo de Brian. Canon: Vincenzo 'Vinny' Lapaglia. Adoptado del Refugio Patitas del Norte.",
  },
  events: [
    {
      date: "2023-12-15",
      event_type: "pet_registered",
      author_role: "owner",
      payload: { acquisition_method: "adopted" },
    },
    {
      date: "2023-12-20",
      event_type: "microchip_implanted",
      author_role: "vet",
      payload: {
        chip_number: "858200200200200",
        country_code: "858",
        implanted_by: "Clínica Veterinaria Recoleta",
        location_on_body: "interscapular_left",
        implant_date_known: true,
      },
    },
    {
      date: "2024-01-10",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP + antirrábica" },
    },
    {
      date: "2024-04-22",
      event_type: "sterilization_performed",
      author_role: "vet",
      payload: { procedure: "castration" },
    },
    {
      date: "2024-09-09",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "wellness" },
    },
    {
      date: "2025-04-15",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual" },
    },
    { date: "2025-10-30", event_type: "weight_recorded", author_role: "vet", payload: { kg: 22 } },
    {
      date: "2026-04-15",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual", next_due_at: "2027-04-15" },
    },
    {
      date: "2026-05-08",
      event_type: "note_added",
      author_role: "owner",
      payload: { category: "rutina", text: "Vinny aprendió a no comer las medias. Eventualmente." },
    },
  ],
};

// ---------------------------------------------------------------------------
// 9. Puss in Boots — DSH cat, San Nicolás (Ignacio), deceased 2025 (canonical 9 lives)
// ---------------------------------------------------------------------------

const puss: Storyline = {
  pet: {
    display_name: "Puss in Boots",
    public_token: "DIM-PUSS-0007",
    species: "cat",
    breed: "Común europeo",
    sex: "male",
    date_of_birth: "2012-06-20",
    color: "Naranja atigrado",
    microchip_id: "858220300400500",
    microchip_country_code: "858",
    microchip_implanted_at: "2026-01-22",
    microchip_implanted_by: "Clínica Veterinaria Recoleta",
    microchip_location: "interscapular_left",
    estimated_weight_kg: 5.3,
    potentially_dangerous_breed: false,
    jurisdiction_country: "AR",
    jurisdiction_province: "CABA",
    jurisdiction_locality: "San Nicolás",
    acquisition_method: "rescued",
    status: "deceased",
    owner: "ignacio",
    photo_file: "puss in b.jpg",
    notes: "Sin chip durante 13 años. 8 incidentes traumáticos previos al chip; muere en el 9no.",
  },
  events: [
    {
      date: "2012-07-10",
      event_type: "shelter_intake_recorded",
      author_role: "shelter",
      payload: { intake_reason: "stray_found", intake_condition: "kitten_orphan" },
      uncommon: true,
    },
    {
      date: "2012-09-15",
      event_type: "pet_registered",
      author_role: "owner",
      payload: { acquisition_method: "rescued" },
    },
    {
      date: "2012-11-20",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "FVRCP" },
    },
    {
      date: "2014-02-22",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "fall",
        severity: "alta",
        injuries_summary: "Caída desde campanario — 'vida #1'",
      },
      uncommon: true,
    },
    {
      date: "2016-01-10",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "fight",
        severity: "moderada",
        injuries_summary: "Pelea con gato vecino — 'vida #2'",
      },
      uncommon: true,
    },
    {
      date: "2018-04-04",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "fall",
        severity: "alta",
        injuries_summary: "Aplastado por araña — 'vida #3'",
      },
      uncommon: true,
    },
    {
      date: "2018-10-10",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "other", title: "Profilaxis dental" },
    },
    {
      date: "2019-08-22",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "other",
        severity: "alta",
        injuries_summary: "Casi se ahoga en el Río de la Plata — 'vida #4'",
      },
      uncommon: true,
    },
    {
      date: "2020-12-25",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "fall",
        severity: "alta",
        injuries_summary: "Caída desde habichuela mágica — 'vida #5'",
      },
      uncommon: true,
    },
    {
      date: "2021-09-15",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "other",
        severity: "alta",
        injuries_summary: "Pisoteado por ogro — 'vida #6'",
      },
      uncommon: true,
    },
    {
      date: "2022-05-30",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "other",
        severity: "alta",
        injuries_summary: "Aplastado por gigante — 'vida #7'",
      },
      uncommon: true,
    },
    {
      date: "2022-09-09",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "other",
        severity: "alta",
        injuries_summary: "Episodio cardíaco durante duelo — 'vida #8'",
      },
      uncommon: true,
    },
    {
      date: "2022-10-22",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "fluoxetina",
        dose: "5 mg",
        frequency: "SID",
        first_dose_at: "2022-10-22",
        schedule_count: 365,
      },
    },
    {
      date: "2024-01-15",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "wellness anual" },
    },
    {
      date: "2025-02-14",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "anual senior" },
    },
    {
      date: "2026-01-22",
      event_type: "microchip_implanted",
      author_role: "vet",
      payload: {
        chip_number: "858220300400500",
        country_code: "858",
        implanted_by: "Clínica Veterinaria Recoleta",
        location_on_body: "interscapular_left",
        implant_date_known: true,
        note: "implantado finalmente tras 14 años — 9na vida",
      },
      uncommon: true,
    },
    {
      date: "2026-03-15",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "fall",
        severity: "fatal",
        injuries_summary: "Caída desde tejado — 9na vida",
      },
      uncommon: true,
    },
    {
      date: "2026-03-15",
      event_type: "death_recorded",
      author_role: "vet",
      location: CABA("San Nicolás"),
      payload: {
        cause: "accident",
        cause_detail: "trauma craneal severo tras caída de 4 metros — 9 vidas usadas",
        confirmed_by_vet: true,
        vet_name: "Dra. Lilian Marrone",
        disposition_method: "owner_burial",
        facility: "Quinta familiar San Antonio de Areco",
        death_at_clinic: true,
        vet_contacted_owner: "yes",
        is_reportable: false,
      },
      uncommon: true,
    },
    {
      date: "2026-03-16",
      event_type: "note_added",
      author_role: "owner",
      payload: {
        category: "despedida",
        text: "Puss — nueve vidas y todavía sentís que te faltó una. Buen viaje, gato bota. — Ignacio",
      },
      uncommon: true,
    },
  ],
};

// ---------------------------------------------------------------------------
// 10. Courage — Mixed-breed toy, Recoleta (Graciela), active
// ---------------------------------------------------------------------------

const courage: Storyline = {
  pet: {
    display_name: "Courage",
    public_token: "DIM-CRGE-0009",
    species: "dog",
    breed: "Mestizo pequeño",
    sex: "male",
    date_of_birth: "2017-04-10",
    color: "Rosa",
    estimated_weight_kg: 4.5,
    potentially_dangerous_breed: false,
    jurisdiction_country: "AR",
    jurisdiction_province: "CABA",
    jurisdiction_locality: "Recoleta",
    acquisition_method: "rescued",
    status: "active",
    owner: "graciela",
    photo_file: "courage.jpg",
    notes:
      "Encontrado en callejón. Sin chip — historia de cuidado paliativo continuo. Curatorial owner: Graciela.",
  },
  events: [
    {
      date: "2017-05-15",
      event_type: "shelter_intake_recorded",
      author_role: "shelter",
      payload: { intake_reason: "stray_found", intake_condition: "underweight + traumatizado" },
      uncommon: true,
    },
    {
      date: "2017-06-01",
      event_type: "pet_registered",
      author_role: "owner",
      payload: { acquisition_method: "rescued" },
    },
    {
      date: "2017-06-15",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "intake_exam", body_condition_score: 2 },
    },
    {
      date: "2017-07-04",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP + antirrábica (catch-up)" },
    },
    {
      date: "2018-02-14",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "other",
        severity: "leve",
        injuries_summary: "Episodio de pánico aguda — explosión cercana",
      },
      uncommon: true,
    },
    {
      date: "2019-04-22",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "trauma — laceraciones por gato vecino" },
    },
    {
      date: "2019-08-08",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "terapia trauma — sesión #1" },
    },
    {
      date: "2021-09-09",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "other", title: "Profilaxis dental" },
    },
    {
      date: "2022-01-10",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: {
        reason: "dermatitis alérgica de contacto",
        diagnosis: "exposición a sustancia no identificada",
      },
    },
    {
      date: "2023-09-09",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "fluoxetina",
        dose: "5 mg",
        frequency: "SID",
        first_dose_at: "2023-09-09",
        schedule_count: 730,
      },
      uncommon: true,
    },
    {
      date: "2024-11-30",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "exposición a sustancia desconocida — tox negativo" },
    },
    {
      date: "2025-08-30",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "picaduras múltiples de abeja" },
    },
    {
      date: "2025-11-11",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "imaging", title: "Eco cardíaca — IM leve" },
    },
    {
      date: "2026-02-14",
      event_type: "pet_profile_updated",
      author_role: "owner",
      payload: { changes: [{ field: "credential_issued", old: null, new: true }] },
    },
    {
      date: "2026-03-30",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "wellness anual" },
    },
    {
      date: "2026-05-10",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "terapia mantenimiento PTSD canino" },
    },
  ],
};

// ---------------------------------------------------------------------------
// 11. Odie — Dachshund mix, Puerto Madero (Ignacio), active, orphaned-owner case
// ---------------------------------------------------------------------------

const odie: Storyline = {
  pet: {
    display_name: "Odie",
    public_token: "DIM-ODIE-0005",
    species: "dog",
    breed: "Mestizo Dachshund/Beagle",
    sex: "male",
    date_of_birth: "2008-03-15",
    color: "Amarillo y marrón",
    estimated_weight_kg: 13.5,
    potentially_dangerous_breed: false,
    jurisdiction_country: "AR",
    jurisdiction_province: "CABA",
    jurisdiction_locality: "Puerto Madero",
    acquisition_method: "rescued",
    status: "active",
    owner: "ignacio",
    photo_file: "OdieCharacter.webp",
    notes:
      "Dueño original 'Lyman' desapareció en 2010 — custodia legalmente reasignada a Jon Arbuckle (en este registro, Ignacio).",
  },
  events: [
    {
      date: "2008-06-20",
      event_type: "shelter_intake_recorded",
      author_role: "shelter",
      payload: { intake_reason: "stray_found" },
      uncommon: true,
    },
    {
      date: "2008-07-05",
      event_type: "pet_registered",
      author_role: "owner",
      payload: { acquisition_method: "rescued" },
    },
    {
      date: "2008-07-08",
      event_type: "vaccination_administered",
      author_role: "vet",
      payload: { vaccine_name: "DHPP + antirrábica" },
    },
    {
      date: "2010-02-14",
      event_type: "custody_dispute_raised",
      author_role: "govt",
      payload: {
        raised_by_role: "govt",
        reason: "Dueño original 'Lyman' en paradero desconocido por >90d",
      },
      uncommon: true,
    },
    {
      date: "2010-02-28",
      event_type: "custody_transfer_proposed",
      author_role: "owner",
      payload: {
        from_user_id: "Lyman",
        to_user_id: "Jon Arbuckle (Ignacio)",
        reason: "owner_missing",
      },
      uncommon: true,
    },
    {
      date: "2010-03-01",
      event_type: "custody_transferred",
      author_role: "owner",
      payload: {
        from_user_id: "Lyman",
        to_user_id: "Ignacio",
        from_role: "owner",
        to_role: "owner",
        reason: "owner_missing > 90d",
      },
      uncommon: true,
    },
    {
      date: "2010-03-05",
      event_type: "custody_dispute_resolved",
      author_role: "govt",
      payload: { outcome: "ownership_transferred" },
    },
    {
      date: "2011-01-25",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "trauma — caída de mesa" },
    },
    {
      date: "2012-02-14",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "other", title: "Profilaxis dental" },
    },
    {
      date: "2012-11-30",
      event_type: "status_changed",
      author_role: "owner",
      location: CABA("Puerto Madero"),
      payload: { from_status: "active", to_status: "lost" },
      uncommon: true,
    },
    {
      date: "2012-12-04",
      event_type: "credential_scanned",
      author_role: "system",
      location: CABA("Puerto Madero"),
      payload: { is_self_scan: false, viewer_authenticated: false, viewer_name: "vecino Pooky" },
    },
    {
      date: "2012-12-04",
      event_type: "status_changed",
      author_role: "owner",
      payload: { from_status: "lost", to_status: "active" },
    },
    {
      date: "2014-04-04",
      event_type: "incident_reported",
      author_role: "owner",
      payload: {
        incident_type: "fight",
        severity: "leve",
        injuries_summary: "Pelea intra-domicilio con gato co-residente",
      },
      uncommon: true,
    },
    {
      date: "2017-04-22",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "reacción alérgica picadura de abeja" },
    },
    {
      date: "2019-06-15",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: {
        sub_kind: "imaging",
        title: "Rx columna — discopatía L1-L2 incipiente (Dachshund)",
      },
    },
    {
      date: "2019-10-31",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "episodio IVDD — manejo conservador + reposo en crate" },
      uncommon: true,
    },
    {
      date: "2020-02-14",
      event_type: "medication_started",
      author_role: "vet",
      payload: {
        drug_name: "gabapentina + meloxicam",
        dose: "10 mg + 0.1 mg/kg",
        frequency: "BID",
        first_dose_at: "2020-02-14",
        schedule_count: 90,
      },
    },
    {
      date: "2023-02-14",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "terapia mantenimiento co-pet conflict" },
    },
    {
      date: "2025-11-25",
      event_type: "clinical_info_logged",
      author_role: "vet",
      payload: { sub_kind: "other", title: "Profilaxis dental senior" },
    },
    {
      date: "2026-04-10",
      event_type: "vet_visit_logged",
      author_role: "vet",
      payload: { reason: "18th-year senior wellness" },
    },
    {
      date: "2026-05-09",
      event_type: "weight_recorded",
      author_role: "vet",
      payload: { kg: 13.5 },
    },
  ],
};

// ===========================================================================
// Aggregated export
// ===========================================================================

export const ORIGINAL_10_STORYLINES: Storyline[] = [
  scooby,
  slh,
  snoopy,
  tom,
  blue,
  bolt,
  brian,
  vinny,
  puss,
  courage,
  odie,
];
