// Pets currently held by the active organization. Lists every active
// ownership row where owner_organization_id = active org. Multiple custody
// rows on the same pet (e.g. shelter_custody + foster) collapse to one card
// — the highest-stakes role wins for the badge.
//
// Sprint 8 PR1: server data-fetcher only. List rendering moved to the
// OrgMascotasBulkList client component so multi-select + bulk vaccination
// can be wired with useState/useTransition.

import { db, ownerships, pets } from "@/db";
import { loadWithTimeout } from "@/lib/analytics/analytics-load";
import { requireOrgAccessByToken } from "@/lib/infra/auth-guards";
import { pluralizeEs } from "@/lib/utils/format";
import { capRows } from "@/lib/utils/list-pagination";
import { trimmedSearchParam } from "@/lib/utils/search-params";
import { getGrantedCapabilities } from "@/src/modules/organizations/infrastructure/authz-resolver";
import { and, countDistinct, desc, eq, ilike, inArray, isNull, notInArray, sql } from "drizzle-orm";
import Link from "next/link";

import { Icon } from "@/components/Icon";
import { CopyButton } from "@/components/ui/CopyButton";
import { OpCallout, OpCrumbs } from "@/components/ui/dashboard";
import { AnalyticsLoadFallback } from "@/components/ui/dashboard/AnalyticsLoadFallback";

import { OrgMascotasBulkList } from "./OrgMascotasBulkList";
import { OrgMascotasFilterBar } from "./OrgMascotasFilterBar";

const ROLE_PRIORITY: Record<string, number> = {
  owner: 4,
  shelter_custody: 3,
  foster: 2,
  co_owner: 1,
  caretaker: 0,
};

// Custody list is capped at 200 rows client-side (stopgap — see #815 audit
// finding #2). Real server-side cursor pagination is future work; for now the
// species/text filters (below) let a large shelter narrow the list instead of
// scrolling an unbounded one, and the truncated banner tells them when rows
// are being hidden by the cap.
const CUSTODY_LIST_CAP = 200;

// SQL-side bound on the custody join (2026-08-09 resilience pass). The cap
// above was applied in JS *after* fetching every active ownership row, so a
// large shelter still paid for the whole set on every page load — the query was
// unbounded, only the rendering was capped. The fetch now takes the newest
// FETCH_CAP rows; the dedup + sort + cap below are unchanged, and because the
// order matches the one the JS applies, the 200 rows that survive are the same
// ones as before for any org under this ceiling.
//
// The headline count does NOT come from this slice — it is its own COUNT
// (see totalActiveCustody), so an org above the ceiling still reads its true
// size instead of the fetch limit.
const CUSTODY_FETCH_CAP = CUSTODY_LIST_CAP * 5;

export default async function OrgMascotasPage({
  params,
  searchParams,
}: {
  params: Promise<{ orgToken: string }>;
  searchParams: Promise<{
    nueva?: string;
    foster?: string;
    fostend?: string;
    adopcion?: string;
    transferido?: string;
    // Species bucket exactly as generated by censo/page.tsx's KPI links
    // (?species=dog|cat|other) — "other" means "not dog and not cat" to
    // match the census grouping (rabbit/guinea_pig/ferret/other all bucket
    // into "Otros" there).
    species?: string;
    q?: string;
    // Deep-link from the org panel "Disponibles" KPI (?adoptionEligible=true):
    // narrows the list to the adoption-eligible pets that tile counts.
    adoptionEligible?: string;
  }>;
}) {
  const { orgToken } = await params;
  const sp = await searchParams;
  const { organization, membership } = await requireOrgAccessByToken(orgToken);
  const granted = await getGrantedCapabilities(membership);
  const canIntake = granted.has("intake.create");
  const canAssignFoster = granted.has("foster.assign");
  const canEndFoster = granted.has("foster.end");
  const canFinalizeAdoption = granted.has("adoption.finalize");
  const canTransfer = granted.has("custody.transfer");
  const canReturnToOwner = granted.has("custody.transfer");
  const canManageAdoptionListing = granted.has("adoption.listing.manage");
  const canEventWrite = granted.has("event.write");
  const canRead = granted.has("pet.read_held") || membership.role === "admin";

  if (!canRead) {
    return (
      <main className="min-h-screen bg-ln-op-page p-6 flex items-center justify-center">
        <div className="max-w-md text-center space-y-4">
          <h1 className="text-title font-semibold text-ln-op-ink">Permiso requerido</h1>
          <p className="text-md text-ln-op-ink-2">
            Para ver el listado de animales necesitás el permiso{" "}
            <code className="text-sm">pet.read_held</code>.
          </p>
          <Link
            href={`/org/${orgToken}`}
            className="inline-block px-4 py-2 rounded-[var(--radius-md)] bg-ln-op-azul text-white text-md hover:bg-ln-op-azul-700"
          >
            Volver al panel
          </Link>
        </div>
      </main>
    );
  }

  // Species/text filters — #815 audit finding #1 (censo→mascotas dead link)
  // and #2 (unbounded list). speciesFilter mirrors censo's own bucketing:
  // dog/cat are literal, "other" is "everything else" (not just species='other').
  const speciesFilter = sp.species === "dog" || sp.species === "cat" ? sp.species : null;
  const isOtherSpecies = sp.species === "other";
  // Q1: a repeated ?q= hands Next a string[] — raw `.trim()` on that throws (500).
  const nameQuery = trimmedSearchParam(sp.q) ?? "";
  const adoptionEligibleFilter = sp.adoptionEligible === "true";

  const whereConditions = [
    eq(ownerships.ownerOrganizationId, organization.id),
    isNull(ownerships.endedAt),
    // An erased pet (art. 16 soft-delete) keeps its sponsorship row alive —
    // the erasure RPC never touches ownerships — but every action on it 404s
    // via resolvePetHolderAccess, so listing it here would be a card of dead
    // ends. Caller-side twin of the resolver's own filter.
    //
    // GUARD-AT-ORIGIN: this ONE condition feeds BOTH `pets` reads below (the
    // list and its count run over the same `whereConditions` array), so a
    // reads-vs-guards scan of this file sees 2 reads / 1 guard and must not
    // read that as a missing filter — the org sweep in
    // public-soft-delete-resolution.test.ts pins this shape explicitly.
    isNull(pets.deletedAt),
  ];
  if (speciesFilter) whereConditions.push(eq(pets.species, speciesFilter));
  if (isOtherSpecies) whereConditions.push(notInArray(pets.species, ["dog", "cat"]));
  if (nameQuery) whereConditions.push(ilike(pets.name, `%${nameQuery}%`));
  // Adoption-eligible narrowing — matches the "Disponibles" KPI population
  // (fetchAvailableForAdoption: active custody pets with adoption_eligible=true).
  if (adoptionEligibleFilter) whereConditions.push(eq(pets.adoptionEligible, true));

  // BOUNDED. Rows and the true total run together: the slice is what gets
  // rendered, the count is what the subtitle claims, and separating them is
  // what lets the fetch have a ceiling without the page lying about its size.
  const listLoad = await loadWithTimeout(
    Promise.all([
      db
        .select({ pet: pets, ownershipRole: ownerships.role, startedAt: ownerships.startedAt })
        .from(pets)
        .innerJoin(ownerships, eq(ownerships.petId, pets.id))
        .where(and(...whereConditions))
        .orderBy(desc(ownerships.startedAt))
        .limit(CUSTODY_FETCH_CAP),
      db
        .select({ n: countDistinct(pets.id) })
        .from(pets)
        .innerJoin(ownerships, eq(ownerships.petId, pets.id))
        .where(and(...whereConditions)),
    ]),
  );
  if (!listLoad.ok) {
    return (
      <main className="min-h-screen bg-ln-op-page p-6">
        <div className="max-w-3xl mx-auto space-y-6">
          <OpCrumbs
            items={[
              { label: "Panel", href: `/org/${orgToken}` },
              { label: "Mascotas en custodia" },
            ]}
          />
          <h1 className="text-title font-semibold text-ln-op-ink">Mascotas en custodia</h1>
          {/* The filter bar and "Registrar ingreso" are built from `sp` and
              `canIntake`, both resolved BEFORE this load — nothing here depends
              on the rows that failed. Dropping them left the operator unable to
              narrow the very query that timed out, or to do the one thing that
              still works. */}
          {canIntake && (
            <Link
              href={`/org/${orgToken}/intake`}
              className="inline-block px-4 py-2 rounded-[var(--radius-md)] bg-ln-op-azul text-white text-md font-medium hover:bg-ln-op-azul-700"
            >
              Registrar ingreso
            </Link>
          )}
          <OrgMascotasFilterBar
            basePath={`/org/${orgToken}/mascotas`}
            query={nameQuery}
            species={sp.species ?? ""}
            adoptionEligible={adoptionEligibleFilter}
          />
          <AnalyticsLoadFallback
            reason={listLoad.reason}
            correlationId={listLoad.id}
            retryHref={`/org/${orgToken}/mascotas`}
          />
        </div>
      </main>
    );
  }
  const [orgRows, totalRow] = listLoad.value;
  const totalActiveCustody = totalRow[0]?.n ?? 0;

  // Collapse multi-custody rows: keep the highest-priority role per pet.
  const byPetId = new Map<string, (typeof orgRows)[number]>();
  for (const row of orgRows) {
    const existing = byPetId.get(row.pet.id);
    if (
      !existing ||
      (ROLE_PRIORITY[row.ownershipRole] ?? -1) > (ROLE_PRIORITY[existing.ownershipRole] ?? -1)
    ) {
      byPetId.set(row.pet.id, row);
    }
  }
  const allCards = Array.from(byPetId.values()).sort(
    (a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime(),
  );

  // Stopgap cap (see CUSTODY_LIST_CAP doc comment above) — bounds what gets
  // rendered/queried-against below even when the filters above still leave a
  // very large result set.
  const { rows: cards, truncated } = capRows(allCards, CUSTODY_LIST_CAP);

  // Which of these pets already have an active foster row? Foster rows have
  // owner_user_id set (NOT owner_organization_id), so they don't show up in
  // the org-join above. Separate query, scoped to the same pet IDs.
  const petIds = cards.map((c) => c.pet.id);
  const fosteredPetIds = new Set<string>();
  if (petIds.length > 0) {
    const fosterRows = await db
      .select({ petId: ownerships.petId })
      .from(ownerships)
      .where(
        and(
          inArray(ownerships.petId, petIds),
          eq(ownerships.role, "foster"),
          isNull(ownerships.endedAt),
        ),
      );
    for (const row of fosterRows) fosteredPetIds.add(row.petId);
  }

  // Which lost pets with shelter_custody already have a pending return proposal?
  // A proposal is pending if there is a custody_transfer_proposed event and no
  // subsequent custody_transferred event resolves it.
  //
  // Replaces the former N+1 loop (2 queries per pet) with one batch query:
  //   1. DISTINCT ON (pet_id) to get the latest proposal per pet.
  //   2. NOT EXISTS subquery to verify no subsequent transfer exists.
  const pendingProposalPetIds = new Set<string>();
  if (petIds.length > 0) {
    const lostPetIds = cards
      .filter((c) => c.pet.status === "lost" && c.ownershipRole === "shelter_custody")
      .map((c) => c.pet.id);

    if (lostPetIds.length > 0) {
      // Single query: latest proposal per pet that has no subsequent transfer.
      const rows = await db.execute<{ pet_id: string }>(sql`
        SELECT lp.pet_id::text AS pet_id
        FROM (
          SELECT DISTINCT ON (pe.pet_id)
            pe.pet_id,
            pe.occurred_at AS proposed_at
          FROM pet_events pe
          WHERE pe.pet_id = ANY(ARRAY[${sql.join(
            lostPetIds.map((id) => sql`${id}::uuid`),
            sql`, `,
          )}])
            AND pe.event_type = 'custody_transfer_proposed'
          ORDER BY pe.pet_id, pe.occurred_at DESC
        ) lp
        WHERE NOT EXISTS (
          SELECT 1 FROM pet_events t
          WHERE t.pet_id = lp.pet_id
            AND t.event_type = 'custody_transferred'
            -- >= (not >) is intentional: a transfer event at the exact proposal
            -- timestamp resolves the proposal (avoids a phantom pending CTA).
            -- Matches lib/owner-dashboard's fetchOpenCasesSweep semantics for
            -- the same concept. The old JS loop used strict >, which would have
            -- left a same-millisecond transfer as falsely pending.
            AND t.occurred_at >= lp.proposed_at
        )
      `);
      for (const row of rows) pendingProposalPetIds.add(row.pet_id);
    }
  }

  const hasActiveFilters = Boolean(
    speciesFilter || isOtherSpecies || nameQuery || adoptionEligibleFilter,
  );

  const recentlyCreated = sp.nueva ?? null;
  const recentlyFostered = sp.foster ?? null;
  const recentlyFosterEnded = sp.fostend ?? null;
  const recentlyAdopted = sp.adopcion ?? null;
  const recentlyTransferred = sp.transferido ?? null;

  // Serialize Sets to arrays — client components cannot receive Set instances
  // as props (not serializable across the Server/Client boundary).
  const fosteredPetIdsArray = Array.from(fosteredPetIds);
  const pendingProposalPetIdsArray = Array.from(pendingProposalPetIds);

  return (
    <main className="min-h-screen bg-ln-op-page p-6">
      <div className="max-w-3xl mx-auto space-y-6">
        <header className="flex items-baseline justify-between gap-3 flex-wrap">
          <div className="space-y-1">
            <OpCrumbs
              items={[
                { label: "Panel", href: `/org/${orgToken}` },
                { label: "Mascotas en custodia" },
              ]}
            />
            {/* Title matches the nav-rail item "Mascotas" (QA 2026-07-03:
                sidebar said Mascotas, page said Animales en custodia). */}
            <h1 className="text-title font-semibold text-ln-op-ink">Mascotas en custodia</h1>
            {/* The count is the org's TRUE size (its own COUNT), not the size
                of the fetched slice — see CUSTODY_FETCH_CAP. */}
            <p className="text-md text-ln-op-ink-2">
              {totalActiveCustody === 0
                ? "Todavía no hay animales registrados a nombre de la organización."
                : `${totalActiveCustody} ${pluralizeEs(totalActiveCustody, "animal")} bajo custodia activa.`}
            </p>
          </div>
          <div className="flex items-center gap-4">
            {/* Exit ramp (org-first readiness #4): the org's own roster, in the
                bulk-import layout so it round-trips. Same anchor idiom as the
                route-based "Exportar CSV →" links on the gob dashboards. Gated
                on nothing extra — reading this page already required
                pet.read_held, which is exactly what the route re-checks.

                The export ignores the filters on purpose (it is the roster, not
                the view), so the link must not react to them either: `allCards`
                is only proof of an empty ORG when nothing is filtering it. With
                a filter active a 0-row screen says nothing about the roster, and
                hiding the exit ramp there would be a lie about what miMAR
                holds. */}
            {(totalActiveCustody > 0 || hasActiveFilters) && (
              <a
                href={`/org/${orgToken}/mascotas/exportar`}
                className="text-md text-ln-op-azul hover:underline"
                download
              >
                Exportar CSV →
              </a>
            )}
            {canIntake && (
              <Link
                href={`/org/${orgToken}/intake`}
                className="px-4 py-2 rounded-[var(--radius-md)] bg-ln-op-azul text-white text-md font-medium hover:bg-ln-op-azul-700"
              >
                Registrar ingreso
              </Link>
            )}
          </div>
        </header>

        {/* PO decision 5 (UI review 2026-08-06): this used to be a GET form with
            a "Filtrar" submit button while every gob/admin bar auto-applies.
            The controls now commit themselves — see OrgMascotasFilterBar for
            the two-mechanism rationale (immediate for selects, debounced for
            the query). */}
        <OrgMascotasFilterBar
          basePath={`/org/${orgToken}/mascotas`}
          query={nameQuery}
          species={sp.species ?? ""}
          adoptionEligible={adoptionEligibleFilter}
        />

        {truncated && (
          <p className="text-sm text-ln-op-mute">
            {/* The denominator is the org's true total, not the fetched slice —
                citing allCards here would understate it for an org above
                CUSTODY_FETCH_CAP, i.e. exactly the org this banner is for. */}
            Mostrando las primeras {CUSTODY_LIST_CAP} de {totalActiveCustody}. Hay más — usá el
            buscador o el filtro de especie para acotar la lista.
          </p>
        )}

        {recentlyCreated && (
          <OpCallout
            title="Ingreso registrado"
            body={
              <>
                Token público: <code className="font-ln-mono">{recentlyCreated}</code>.
                <CopyButton text={recentlyCreated} />
              </>
            }
            icon={<Icon name="check-circle" decorative />}
          />
        )}
        {recentlyFostered && (
          <OpCallout
            title="Tránsito asignado"
            body={
              <>
                Tránsito asignado para <code className="font-ln-mono">{recentlyFostered}</code>.
                <CopyButton text={recentlyFostered} />
              </>
            }
            icon={<Icon name="casa" decorative />}
          />
        )}
        {recentlyFosterEnded && (
          <OpCallout
            title="Tránsito cerrado"
            body={
              <>
                Tránsito cerrado para <code className="font-ln-mono">{recentlyFosterEnded}</code>.
                <CopyButton text={recentlyFosterEnded} />
              </>
            }
            icon={<Icon name="check-circle" decorative />}
          />
        )}
        {recentlyTransferred && (
          <OpCallout
            title="Custodia transferida"
            body={
              <>
                Custodia transferida para{" "}
                <code className="font-ln-mono">{recentlyTransferred}</code>.
                <CopyButton text={recentlyTransferred} /> El animal sale del listado y aparece en el
                destino.
              </>
            }
            icon={<Icon name="transferencia" decorative />}
          />
        )}
        {recentlyAdopted && (
          <OpCallout
            title="Adopción finalizada"
            body={
              <>
                Adopción finalizada para <code className="font-ln-mono">{recentlyAdopted}</code>.
                <CopyButton text={recentlyAdopted} /> El animal pasa a un nuevo dueño y sale del
                listado de custodia.{" "}
                <Link
                  href={`/org/${orgToken}/mascotas/${recentlyAdopted}`}
                  className="underline hover:no-underline"
                >
                  Ver mascota
                </Link>{" "}
                (si hace falta revertirla, la opción está ahí).
              </>
            }
            icon={<Icon name="check-circle" decorative />}
          />
        )}

        <OrgMascotasBulkList
          hasActiveFilters={hasActiveFilters}
          cards={cards.map((c) => ({
            petId: c.pet.id,
            publicToken: c.pet.publicToken,
            name: c.pet.name,
            species: c.pet.species,
            breed: c.pet.breed ?? null,
            color: c.pet.color ?? null,
            dateOfBirth: c.pet.dateOfBirth ?? null,
            birthDateIsEstimated: c.pet.birthDateIsEstimated,
            status: c.pet.status,
            adoptionEligible: c.pet.adoptionEligible ?? null,
            adoptionListedAt: c.pet.adoptionListedAt ? c.pet.adoptionListedAt.toISOString() : null,
            adoptionListingPausedAt: c.pet.adoptionListingPausedAt
              ? c.pet.adoptionListingPausedAt.toISOString()
              : null,
            ownershipRole: c.ownershipRole,
            startedAt: c.startedAt.toISOString(),
          }))}
          fosteredPetIds={fosteredPetIdsArray}
          pendingProposalPetIds={pendingProposalPetIdsArray}
          orgToken={orgToken}
          canIntake={canIntake}
          canAssignFoster={canAssignFoster}
          canEndFoster={canEndFoster}
          canFinalizeAdoption={canFinalizeAdoption}
          canTransfer={canTransfer}
          canReturnToOwner={canReturnToOwner}
          canManageAdoptionListing={canManageAdoptionListing}
          canEventWrite={canEventWrite}
        />

        <footer className="pt-4 border-t border-ln-op-line">
          <Link
            href={`/org/${orgToken}`}
            className="text-sm text-ln-op-mute underline hover:text-ln-op-ink"
          >
            ← Volver al panel
          </Link>
        </footer>
      </div>
    </main>
  );
}
