// The committed official local-government reference, typed for the plan.
// Generated by scripts/generate-locality-gobierno-local.ts (see its header for
// the sources and the rule); never edited by hand. Kept out of
// authority-units-plan.ts so the plan stays a pure function of its inputs and
// its tests feed it fixtures.

import type { LocalGovernmentReference } from "@/lib/place/authority-units-plan";
import reference from "@/lib/reference/locality-gobierno-local.json";

export const OFFICIAL_LOCAL_GOVERNMENTS = reference as unknown as LocalGovernmentReference;
