// AUTO-GENERATED by scripts/prep-geo-representative-points.ts — do not hand-edit.
// Regenerate: pnpm tsx scripts/prep-geo-representative-points.ts
//
// Representative point (pole of inaccessibility, via polylabel) for every
// province and department polygon in public/geo/{ar-provinces,ar-departments}
// .geojson. Guarantees the point lands on the unit's own (largest) landmass —
// unlike an arithmetic mean of member-locality coordinates, which can fall in
// open water for a concave/multi-part geography (Tierra del Fuego / AR-V:
// its province polygon spans Isla Grande + the Malvinas/Georgias claim +
// minor islands — averaging locality coords across those parts drifts into
// the South Atlantic). Consumed by:
//   - src/modules/panorama/infrastructure/repository.ts (province-level
//     aggregated point cells — replaces the runtime AVG(ar_localities.lat/lng))
//   - src/modules/panorama/application/build-features.ts (department fold —
//     replaces the unweighted average of locality centroids)
//
// Placement-only: does not affect k-anon/suppression or which units get a
// marker, and is NOT jitter (one deterministic point per unit, not noise).

export type RepresentativePoint = { lat: number; lng: number };

/** ISO 3166-2:AR province code (e.g. "AR-V") → representative point. */
export const PROVINCE_REPRESENTATIVE_POINTS: Record<string, RepresentativePoint> = {
  "AR-A": { lat: -23.02153, lng: -63.31731 }, // Salta
  "AR-B": { lat: -36.39836, lng: -60.27867 }, // Buenos Aires
  "AR-C": { lat: -34.61091, lng: -58.45828 }, // CABA
  "AR-D": { lat: -32.99851, lng: -66.15229 }, // San Luis
  "AR-E": { lat: -32.39047, lng: -59.40109 }, // Entre Ríos
  "AR-F": { lat: -29.83114, lng: -66.63145 }, // La Rioja
  "AR-G": { lat: -27.97484, lng: -63.36174 }, // Santiago del Estero
  "AR-H": { lat: -26.8487, lng: -60.56048 }, // Chaco
  "AR-J": { lat: -30.85092, lng: -68.83309 }, // San Juan
  "AR-K": { lat: -27.19976, lng: -67.23042 }, // Catamarca
  "AR-L": { lat: -37.39056, lng: -64.81674 }, // La Pampa
  "AR-M": { lat: -34.48824, lng: -68.302 }, // Mendoza
  "AR-N": { lat: -26.74266, lng: -54.27603 }, // Misiones
  "AR-P": { lat: -25.59223, lng: -58.83145 }, // Formosa
  "AR-Q": { lat: -38.40708, lng: -69.64252 }, // Neuquén
  "AR-R": { lat: -40.32615, lng: -67.01055 }, // Río Negro
  "AR-S": { lat: -30.06978, lng: -60.84275 }, // Santa Fe
  "AR-T": { lat: -26.80162, lng: -65.28363 }, // Tucumán
  "AR-U": { lat: -44.00341, lng: -68.88639 }, // Chubut
  "AR-V": { lat: -54.25511, lng: -68.02355 }, // Tierra del Fuego
  "AR-W": { lat: -28.64936, lng: -57.76957 }, // Corrientes
  "AR-X": { lat: -31.29327, lng: -63.76759 }, // Córdoba
  "AR-Y": { lat: -22.74344, lng: -66.02931 }, // Jujuy
  "AR-Z": { lat: -48.16182, lng: -69.92164 }, // Santa Cruz
};

/** INDEC 5-digit department code (e.g. "94015") → representative point. */
export const DEPARTMENT_REPRESENTATIVE_POINTS: Record<string, RepresentativePoint> = {
  "06007": { lat: -37.18115, lng: -63.07435 }, // Adolfo Alsina
  "06014": { lat: -38.04181, lng: -60.04375 }, // Adolfo Gonzales Chaves
  "06021": { lat: -35.15006, lng: -60.22528 }, // Alberti
  "06028": { lat: -34.84681, lng: -58.375 }, // Almirante Brown
  "06035": { lat: -34.67817, lng: -58.34117 }, // Avellaneda
  "06042": { lat: -37.04632, lng: -58.56145 }, // Ayacucho
  "06049": { lat: -36.79178, lng: -59.66882 }, // Azul
  "06056": { lat: -38.61751, lng: -62.24384 }, // Bahía Blanca
  "06063": { lat: -37.76329, lng: -58.24309 }, // Balcarce
  "06070": { lat: -33.94465, lng: -59.49363 }, // Baradero
  "06077": { lat: -33.96433, lng: -60.06925 }, // Arrecifes
  "06084": { lat: -37.63379, lng: -59.70026 }, // Benito Juárez
  "06091": { lat: -34.80998, lng: -58.13919 }, // Berazategui
  "06098": { lat: -34.90744, lng: -57.83239 }, // Berisso
  "06105": { lat: -36.32737, lng: -61.1667 }, // Bolívar
  "06112": { lat: -35.13185, lng: -60.59425 }, // Bragado
  "06119": { lat: -35.21713, lng: -58.21559 }, // Brandsen
  "06126": { lat: -34.1523, lng: -58.8771 }, // Campana
  "06134": { lat: -35.11188, lng: -58.73382 }, // Cañuelas
  "06140": { lat: -34.15564, lng: -59.85459 }, // Capitán Sarmiento
  "06147": { lat: -35.81741, lng: -61.30794 }, // Carlos Casares
  "06154": { lat: -35.34906, lng: -62.46456 }, // Carlos Tejedor
  "06161": { lat: -34.4006, lng: -59.88629 }, // Carmen de Areco
  "06168": { lat: -35.98848, lng: -57.52338 }, // Castelli
  "06175": { lat: -33.95478, lng: -61.11177 }, // Colón
  "06182": { lat: -38.83359, lng: -61.83408 }, // Coronel de Marina Leonardo Rosales
  "06189": { lat: -38.62121, lng: -61.09022 }, // Coronel Dorrego
  "06196": { lat: -38.02403, lng: -61.17739 }, // Coronel Pringles
  "06203": { lat: -37.38885, lng: -62.01053 }, // Coronel Suárez
  "06210": { lat: -34.64153, lng: -60.48053 }, // Chacabuco
  "06218": { lat: -35.54354, lng: -57.99521 }, // Chascomús
  "06224": { lat: -34.88797, lng: -59.99015 }, // Chivilcoy
  "06231": { lat: -36.7341, lng: -61.8081 }, // Daireaux
  "06238": { lat: -36.44671, lng: -57.60888 }, // Dolores
  "06245": { lat: -34.83805, lng: -57.99505 }, // Ensenada
  "06252": { lat: -34.33935, lng: -58.80503 }, // Escobar
  "06260": { lat: -34.86488, lng: -58.46178 }, // Esteban Echeverría
  "06266": { lat: -34.31739, lng: -59.11745 }, // Exaltación de la Cruz
  "06270": { lat: -34.87335, lng: -58.56615 }, // Ezeiza
  "06274": { lat: -34.85172, lng: -58.24202 }, // Florencio Varela
  "06277": { lat: -34.8446, lng: -62.4574 }, // Florentino Ameghino
  "06280": { lat: -38.18543, lng: -58.05238 }, // General Alvarado
  "06287": { lat: -36.06803, lng: -60.28016 }, // General Alvear
  "06294": { lat: -34.24608, lng: -61.30782 }, // General Arenales
  "06301": { lat: -35.90812, lng: -58.57118 }, // General Belgrano
  "06308": { lat: -36.67503, lng: -57.96377 }, // General Guido
  "06315": { lat: -37.22303, lng: -57.27126 }, // General Juan Madariaga
  "06322": { lat: -37.37282, lng: -61.26663 }, // General La Madrid
  "06329": { lat: -34.92841, lng: -58.95909 }, // General Las Heras
  "06336": { lat: -36.64075, lng: -56.94435 }, // General Lavalle
  "06343": { lat: -35.47125, lng: -58.34711 }, // General Paz
  "06351": { lat: -34.71791, lng: -62.01589 }, // General Pinto
  "06357": { lat: -37.9446, lng: -57.71343 }, // General Pueyrredón
  "06364": { lat: -34.67882, lng: -59.01994 }, // General Rodríguez
  "06371": { lat: -34.5507, lng: -58.5723 }, // General San Martín
  "06385": { lat: -35.00979, lng: -61.03139 }, // General Viamonte
  "06392": { lat: -34.77014, lng: -63.00136 }, // General Villegas
  "06399": { lat: -36.82634, lng: -62.4755 }, // Guaminí
  "06406": { lat: -36.31942, lng: -61.74788 }, // Hipólito Yrigoyen
  "06408": { lat: -34.5993, lng: -58.64954 }, // Hurlingham
  "06410": { lat: -34.63605, lng: -58.68883 }, // Ituzaingó
  "06412": { lat: -34.51217, lng: -58.77867 }, // José C. Paz
  "06413": { lat: -34.54293, lng: -60.93103 }, // Junín
  "06420": { lat: -36.91355, lng: -56.71804 }, // La Costa
  "06427": { lat: -34.69974, lng: -58.56154 }, // La Matanza
  "06434": { lat: -34.70758, lng: -58.39802 }, // Lanús
  "06441": { lat: -35.01712, lng: -57.9934 }, // La Plata
  "06448": { lat: -37.50698, lng: -60.67943 }, // Laprida
  "06455": { lat: -36.01585, lng: -59.17636 }, // Las Flores
  "06462": { lat: -34.49949, lng: -61.62143 }, // Leandro N. Alem
  "06466": { lat: -35.85286, lng: -57.90884 }, // Lezama
  "06469": { lat: -35.19743, lng: -61.75848 }, // Lincoln
  "06476": { lat: -38.19072, lng: -58.59473 }, // Lobería
  "06483": { lat: -35.22483, lng: -59.13308 }, // Lobos
  "06490": { lat: -34.76504, lng: -58.42456 }, // Lomas de Zamora
  "06497": { lat: -34.5453, lng: -59.17637 }, // Luján
  "06505": { lat: -35.11925, lng: -57.68603 }, // Magdalena
  "06511": { lat: -36.95603, lng: -57.68482 }, // Maipú
  "06515": { lat: -34.48016, lng: -58.72029 }, // Malvinas Argentinas
  "06518": { lat: -37.55396, lng: -57.55881 }, // Mar Chiquita
  "06525": { lat: -34.795, lng: -58.85343 }, // Marcos Paz
  "06532": { lat: -34.69382, lng: -59.39956 }, // Mercedes
  "06539": { lat: -34.71125, lng: -58.74288 }, // Merlo
  "06547": { lat: -35.52366, lng: -58.72654 }, // Monte
  "06553": { lat: -38.95229, lng: -61.36539 }, // Monte Hermoso
  "06560": { lat: -34.61405, lng: -58.80775 }, // Moreno
  "06568": { lat: -34.65581, lng: -58.63262 }, // Morón
  "06574": { lat: -35.02913, lng: -59.43876 }, // Navarro
  "06581": { lat: -38.43116, lng: -59.07368 }, // Necochea
  "06588": { lat: -35.50532, lng: -60.90304 }, // 9 de Julio
  "06595": { lat: -36.95274, lng: -60.4421 }, // Olavarría
  "06602": { lat: -40.02254, lng: -62.89262 }, // Patagones
  "06609": { lat: -35.86322, lng: -61.94748 }, // Pehuajó
  "06616": { lat: -36.28668, lng: -63.20421 }, // Pellegrini
  "06623": { lat: -33.87828, lng: -60.52529 }, // Pergamino
  "06630": { lat: -36.2296, lng: -58.33091 }, // Pila
  "06638": { lat: -34.46896, lng: -58.88161 }, // Pilar
  "06644": { lat: -37.10935, lng: -56.86985 }, // Pinamar
  "06648": { lat: -34.93791, lng: -58.42759 }, // Presidente Perón
  "06651": { lat: -38.18827, lng: -63.07152 }, // Puán
  "06655": { lat: -35.39588, lng: -57.32991 }, // Punta Indio
  "06658": { lat: -34.72841, lng: -58.27421 }, // Quilmes
  "06665": { lat: -33.59287, lng: -60.04878 }, // Ramallo
  "06672": { lat: -36.48333, lng: -58.8806 }, // Rauch
  "06679": { lat: -35.56274, lng: -63.09416 }, // Rivadavia
  "06686": { lat: -34.2402, lng: -60.73543 }, // Rojas
  "06693": { lat: -35.5358, lng: -59.22488 }, // Roque Pérez
  "06700": { lat: -37.76075, lng: -62.42205 }, // Saavedra
  "06707": { lat: -35.65324, lng: -59.61367 }, // Saladillo
  "06714": { lat: -34.29087, lng: -60.34083 }, // Salto
  "06721": { lat: -36.69522, lng: -63.01914 }, // Salliqueló
  "06728": { lat: -34.43273, lng: -59.44502 }, // San Andrés de Giles
  "06735": { lat: -34.26613, lng: -59.59074 }, // San Antonio de Areco
  "06742": { lat: -38.33285, lng: -59.58351 }, // San Cayetano
  "06749": { lat: -34.1583, lng: -58.50693 }, // San Fernando
  "06756": { lat: -34.48697, lng: -58.53718 }, // San Isidro
  "06760": { lat: -34.56001, lng: -58.71829 }, // San Miguel
  "06763": { lat: -33.52011, lng: -60.31406 }, // San Nicolás
  "06770": { lat: -33.78305, lng: -59.78815 }, // San Pedro
  "06778": { lat: -35.1064, lng: -58.47817 }, // San Vicente
  "06784": { lat: -34.78624, lng: -59.67676 }, // Suipacha
  "06791": { lat: -37.26283, lng: -59.28532 }, // Tandil
  "06798": { lat: -36.47125, lng: -60.19327 }, // Tapalqué
  "06805": { lat: -34.36288, lng: -58.60484 }, // Tigre
  "06812": { lat: -36.3715, lng: -57.21147 }, // Tordillo
  "06819": { lat: -38.1858, lng: -62.12406 }, // Tornquist
  "06826": { lat: -36.03236, lng: -62.70625 }, // Trenque Lauquen
  "06833": { lat: -38.55832, lng: -60.26229 }, // Tres Arroyos
  "06840": { lat: -34.61384, lng: -58.55119 }, // Tres de Febrero
  "06847": { lat: -36.51677, lng: -62.84453 }, // Tres Lomas
  "06854": { lat: -35.50544, lng: -60.24733 }, // 25 de Mayo
  "06861": { lat: -34.52657, lng: -58.5046 }, // Vicente López
  "06868": { lat: -37.42239, lng: -57.10257 }, // Villa Gesell
  "06875": { lat: -39.04317, lng: -62.82593 }, // Villarino
  "06882": { lat: -34.03401, lng: -59.1319 }, // Zárate
  "10007": { lat: -27.99144, lng: -65.93006 }, // Ambato
  "10014": { lat: -28.84123, lng: -65.51669 }, // Ancasti
  "10021": { lat: -27.52018, lng: -66.30977 }, // Andalgalá
  "10028": { lat: -25.96643, lng: -67.68168 }, // Antofagasta de la Sierra
  "10035": { lat: -27.16761, lng: -66.93331 }, // Belén
  "10042": { lat: -28.74487, lng: -66.04968 }, // Capayán
  "10049": { lat: -28.41045, lng: -65.83865 }, // Capital
  "10056": { lat: -28.4153, lng: -65.3758 }, // El Alto
  "10063": { lat: -28.29992, lng: -65.75182 }, // Fray Mamerto Esquiú
  "10070": { lat: -29.33559, lng: -65.16056 }, // La Paz
  "10077": { lat: -28.0667, lng: -65.66767 }, // Paclín
  "10084": { lat: -28.22458, lng: -66.30978 }, // Pomán
  "10091": { lat: -26.87573, lng: -66.29483 }, // Santa María
  "10098": { lat: -28.02188, lng: -65.35635 }, // Santa Rosa
  "10105": { lat: -27.51096, lng: -67.93267 }, // Tinogasta
  "10112": { lat: -28.53696, lng: -65.69786 }, // Valle Viejo
  "14007": { lat: -32.18755, lng: -64.65582 }, // Calamuchita
  "14014": { lat: -31.41675, lng: -64.1836 }, // Capital
  "14021": { lat: -31.13797, lng: -64.06775 }, // Colón
  "14028": { lat: -30.86331, lng: -64.92194 }, // Cruz del Eje
  "14035": { lat: -34.58902, lng: -64.68332 }, // General Roca
  "14042": { lat: -32.63768, lng: -63.3361 }, // General San Martín
  "14049": { lat: -30.33925, lng: -64.69128 }, // Ischilín
  "14056": { lat: -33.47616, lng: -63.53188 }, // Juárez Celman
  "14063": { lat: -32.92191, lng: -62.15529 }, // Marcos Juárez
  "14070": { lat: -31.03506, lng: -65.50956 }, // Minas
  "14077": { lat: -31.45593, lng: -65.57647 }, // Pocho
  "14084": { lat: -34.14798, lng: -63.60049 }, // Presidente Roque Sáenz Peña
  "14091": { lat: -31.24111, lng: -64.56262 }, // Punilla
  "14098": { lat: -33.42362, lng: -64.56333 }, // Río Cuarto
  "14105": { lat: -30.93996, lng: -63.39068 }, // Río Primero
  "14112": { lat: -30.04138, lng: -63.05276 }, // Río Seco
  "14119": { lat: -31.69362, lng: -63.42949 }, // Río Segundo
  "14126": { lat: -31.63507, lng: -64.96746 }, // San Alberto
  "14133": { lat: -32.06783, lng: -65.0923 }, // San Javier
  "14140": { lat: -31.3144, lng: -62.536 }, // San Justo
  "14147": { lat: -31.68781, lng: -64.19794 }, // Santa María
  "14154": { lat: -29.75088, lng: -64.16685 }, // Sobremonte
  "14161": { lat: -32.24047, lng: -63.75386 }, // Tercero Arriba
  "14168": { lat: -30.74039, lng: -63.89529 }, // Totoral
  "14175": { lat: -29.80201, lng: -64.71549 }, // Tulumba
  "14182": { lat: -32.64841, lng: -62.77312 }, // Unión
  "18007": { lat: -28.47226, lng: -58.89009 }, // Bella Vista
  "18014": { lat: -27.51887, lng: -57.56067 }, // Berón de Astrada
  "18021": { lat: -27.53123, lng: -58.77067 }, // Capital
  "18028": { lat: -28.39537, lng: -57.98941 }, // Concepción
  "18035": { lat: -29.68419, lng: -58.3113 }, // Curuzú Cuatiá
  "18042": { lat: -27.85971, lng: -58.66732 }, // Empedrado
  "18049": { lat: -30.03473, lng: -59.29592 }, // Esquina
  "18056": { lat: -28.86249, lng: -56.51785 }, // General Alvear
  "18063": { lat: -27.77512, lng: -57.84511 }, // General Paz
  "18070": { lat: -29.45376, lng: -59.28514 }, // Goya
  "18077": { lat: -27.35696, lng: -58.21854 }, // Itatí
  "18084": { lat: -28.04162, lng: -57.05602 }, // Ituzaingó
  "18091": { lat: -28.94064, lng: -59.04728 }, // Lavalle
  "18098": { lat: -28.05629, lng: -58.24398 }, // Mburucuyá
  "18105": { lat: -29.10216, lng: -57.92087 }, // Mercedes
  "18112": { lat: -30.22306, lng: -57.83691 }, // Monte Caseros
  "18119": { lat: -29.51102, lng: -57.23709 }, // Paso de los Libres
  "18126": { lat: -28.18172, lng: -58.55053 }, // Saladas
  "18133": { lat: -27.40633, lng: -58.57992 }, // San Cosme
  "18140": { lat: -27.60209, lng: -58.35115 }, // San Luis del Palmar
  "18147": { lat: -28.94079, lng: -56.94199 }, // San Martín
  "18154": { lat: -27.97018, lng: -57.54958 }, // San Miguel
  "18161": { lat: -28.76315, lng: -58.70485 }, // San Roque
  "18168": { lat: -28.22548, lng: -56.18295 }, // Santo Tomé
  "18175": { lat: -30.02661, lng: -58.85959 }, // Sauce
  "22007": { lat: -25.27374, lng: -62.59643 }, // Almirante Brown
  "22014": { lat: -26.92505, lng: -58.73679 }, // Bermejo
  "22021": { lat: -26.78536, lng: -60.46129 }, // Comandante Fernández
  "22028": { lat: -27.25723, lng: -61.10704 }, // Chacabuco
  "22036": { lat: -27.2949, lng: -61.51713 }, // 12 de Octubre
  "22039": { lat: -27.6366, lng: -61.4128 }, // 2 de Abril
  "22043": { lat: -27.8679, lng: -61.12667 }, // Fray Justo Santa María de Oro
  "22049": { lat: -26.77176, lng: -61.10121 }, // General Belgrano
  "22056": { lat: -27.16282, lng: -59.41681 }, // General Donovan
  "22063": { lat: -24.98879, lng: -61.74185 }, // General Güemes
  "22070": { lat: -26.70578, lng: -60.75049 }, // Independencia
  "22077": { lat: -27.3064, lng: -59.1755 }, // Libertad
  "22084": { lat: -26.57412, lng: -59.17651 }, // Libertador General San Martín
  "22091": { lat: -26.32922, lng: -60.42843 }, // Maipú
  "22098": { lat: -27.67696, lng: -60.73574 }, // Mayor Luis J. Fontana
  "22105": { lat: -26.78166, lng: -61.46194 }, // 9 de Julio
  "22112": { lat: -27.25443, lng: -60.67427 }, // O'Higgins
  "22119": { lat: -27.087, lng: -59.77656 }, // Presidencia de la Plaza
  "22126": { lat: -27.23544, lng: -58.91884 }, // 1° de Mayo
  "22133": { lat: -26.40692, lng: -60.09795 }, // Quitilipi
  "22140": { lat: -27.72781, lng: -59.13012 }, // San Fernando
  "22147": { lat: -27.22672, lng: -60.36258 }, // San Lorenzo
  "22154": { lat: -26.90363, lng: -59.48048 }, // Sargento Cabral
  "22161": { lat: -27.65966, lng: -59.87376 }, // Tapenagá
  "22168": { lat: -26.98595, lng: -60.0893 }, // 25 de Mayo
  "26007": { lat: -42.42552, lng: -65.46582 }, // Biedma
  "26014": { lat: -42.44011, lng: -71.04488 }, // Cushamen
  "26021": { lat: -45.25684, lng: -67.79326 }, // Escalante
  "26028": { lat: -44.42552, lng: -66.17137 }, // Florentino Ameghino
  "26035": { lat: -43.20509, lng: -71.3721 }, // Futaleufú
  "26042": { lat: -43.32109, lng: -66.07338 }, // Gaiman
  "26049": { lat: -42.76353, lng: -68.9414 }, // Gastre
  "26056": { lat: -43.22103, lng: -70.10016 }, // Languiñeo
  "26063": { lat: -43.88693, lng: -67.20212 }, // Mártires
  "26070": { lat: -44.0096, lng: -68.8334 }, // Paso de Indios
  "26077": { lat: -43.10341, lng: -65.18759 }, // Rawson
  "26084": { lat: -45.33216, lng: -70.64882 }, // Río Senguer
  "26091": { lat: -45.34509, lng: -69.00285 }, // Sarmiento
  "26098": { lat: -44.21945, lng: -70.47605 }, // Tehuelches
  "26105": { lat: -42.43886, lng: -67.17684 }, // Telsen
  "30008": { lat: -32.00018, lng: -58.37331 }, // Colón
  "30015": { lat: -31.28639, lng: -58.20335 }, // Concordia
  "30021": { lat: -32.14838, lng: -60.50309 }, // Diamante
  "30028": { lat: -30.6279, lng: -58.26047 }, // Federación
  "30035": { lat: -30.935, lng: -58.92649 }, // Federal
  "30042": { lat: -30.44328, lng: -58.697 }, // Feliciano
  "30049": { lat: -32.90864, lng: -59.52424 }, // Gualeguay
  "30056": { lat: -33.0671, lng: -58.80813 }, // Gualeguaychú
  "30063": { lat: -33.71447, lng: -58.70885 }, // Islas del Ibicuy
  "30070": { lat: -31.15102, lng: -59.598 }, // La Paz
  "30077": { lat: -32.21872, lng: -59.76972 }, // Nogoyá
  "30084": { lat: -31.67013, lng: -60.03786 }, // Paraná
  "30088": { lat: -31.61312, lng: -58.41805 }, // San Salvador
  "30091": { lat: -32.23557, lng: -59.29114 }, // Tala
  "30098": { lat: -32.27862, lng: -58.85226 }, // Uruguay
  "30105": { lat: -32.82205, lng: -60.31724 }, // Victoria
  "30113": { lat: -31.7227, lng: -58.99535 }, // Villaguay
  "34007": { lat: -24.03799, lng: -61.38137 }, // Bermejo
  "34014": { lat: -25.9079, lng: -58.3212 }, // Formosa
  "34021": { lat: -26.54677, lng: -58.42738 }, // Laishi
  "34028": { lat: -23.90355, lng: -62.088 }, // Matacos
  "34035": { lat: -24.9233, lng: -59.83497 }, // Patiño
  "34042": { lat: -25.12255, lng: -58.64215 }, // Pilagás
  "34049": { lat: -25.30516, lng: -58.12183 }, // Pilcomayo
  "34056": { lat: -25.82004, lng: -59.27798 }, // Pirané
  "34063": { lat: -23.25019, lng: -62.09699 }, // Ramón Lista
  "38007": { lat: -22.91947, lng: -65.96504 }, // Cochinoca
  "38014": { lat: -24.45233, lng: -65.05032 }, // El Carmen
  "38021": { lat: -24.15742, lng: -65.55639 }, // Dr. Manuel Belgrano
  "38028": { lat: -23.09013, lng: -65.43306 }, // Humahuaca
  "38035": { lat: -23.68781, lng: -64.73056 }, // Ledesma
  "38042": { lat: -24.19139, lng: -65.14259 }, // Palpalá
  "38049": { lat: -22.68792, lng: -66.76337 }, // Rinconada
  "38056": { lat: -24.3635, lng: -65.43283 }, // San Antonio
  "38063": { lat: -24.23004, lng: -64.88126 }, // San Pedro
  "38070": { lat: -24.05585, lng: -64.41846 }, // Santa Bárbara
  "38077": { lat: -22.08519, lng: -66.10296 }, // Santa Catalina
  "38084": { lat: -23.41727, lng: -66.69405 }, // Susques
  "38094": { lat: -23.5543, lng: -65.31095 }, // Tilcara
  "38098": { lat: -23.65098, lng: -65.70057 }, // Tumbaya
  "38105": { lat: -23.50627, lng: -65.00467 }, // Valle Grande
  "38112": { lat: -22.29395, lng: -65.46678 }, // Yavi
  "42007": { lat: -37.03225, lng: -63.7797 }, // Atreucó
  "42014": { lat: -38.65717, lng: -63.79562 }, // Caleu Caleu
  "42021": { lat: -36.48628, lng: -64.16842 }, // Capital
  "42028": { lat: -36.58168, lng: -63.66487 }, // Catriló
  "42035": { lat: -36.0334, lng: -64.5238 }, // Conhelo
  "42042": { lat: -38.21013, lng: -66.21544 }, // Curacó
  "42049": { lat: -36.3957, lng: -66.57276 }, // Chalileo
  "42056": { lat: -35.22989, lng: -63.66035 }, // Chapaleufú
  "42063": { lat: -36.4002, lng: -67.71175 }, // Chical Co
  "42070": { lat: -37.4834, lng: -63.7827 }, // Guatraché
  "42077": { lat: -37.9791, lng: -63.95675 }, // Hucal
  "42084": { lat: -38.251, lng: -65.0798 }, // Lihuel Calel
  "42091": { lat: -37.2408, lng: -66.5523 }, // Limay Mahuida
  "42098": { lat: -36.47815, lng: -65.5341 }, // Loventué
  "42105": { lat: -35.67963, lng: -63.66249 }, // Maracó
  "42112": { lat: -37.24999, lng: -67.57504 }, // Puelén
  "42119": { lat: -36.13035, lng: -63.6643 }, // Quemú Quemú
  "42126": { lat: -35.40832, lng: -64.7962 }, // Rancul
  "42133": { lat: -35.23067, lng: -64.20985 }, // Realicó
  "42140": { lat: -36.6951, lng: -64.7796 }, // Toay
  "42147": { lat: -35.63186, lng: -64.2144 }, // Trenel
  "42154": { lat: -37.33561, lng: -65.19033 }, // Utracán
  "46007": { lat: -28.47225, lng: -66.71651 }, // Arauco
  "46014": { lat: -29.39714, lng: -66.36892 }, // Capital
  "46021": { lat: -28.83694, lng: -66.93208 }, // Castro Barros
  "46028": { lat: -29.49484, lng: -68.06952 }, // General Felipe Varela
  "46035": { lat: -30.11674, lng: -65.75272 }, // Chamical
  "46042": { lat: -29.47276, lng: -67.38605 }, // Chilecito
  "46049": { lat: -28.71283, lng: -67.56436 }, // Famatina
  "46056": { lat: -30.37586, lng: -66.66469 }, // Ángel Vicente Peñaloza
  "46063": { lat: -30.56848, lng: -65.7681 }, // General Belgrano
  "46070": { lat: -30.85101, lng: -66.84624 }, // General Juan Facundo Quiroga
  "46077": { lat: -28.84558, lng: -68.69224 }, // General Lamadrid
  "46084": { lat: -31.00952, lng: -66.03415 }, // General Ortiz de Ocampo
  "46091": { lat: -31.58216, lng: -66.02389 }, // General San Martín
  "46098": { lat: -28.16445, lng: -68.78126 }, // Vinchina
  "46105": { lat: -30.16203, lng: -67.23979 }, // Independencia
  "46112": { lat: -31.40321, lng: -66.66591 }, // Rosario Vera Peñaloza
  "46119": { lat: -28.51383, lng: -67.12854 }, // San Blas de Los Sauces
  "46126": { lat: -29.19032, lng: -67.05957 }, // Sanagasta
  "50007": { lat: -32.8834, lng: -68.937 }, // Capital
  "50014": { lat: -35.14344, lng: -67.0905 }, // General Alvear
  "50021": { lat: -32.93205, lng: -68.91407 }, // Godoy Cruz
  "50028": { lat: -32.89415, lng: -68.71575 }, // Guaymallén
  "50035": { lat: -33.11847, lng: -68.57132 }, // Junín
  "50042": { lat: -33.50248, lng: -67.41722 }, // La Paz
  "50049": { lat: -32.38157, lng: -69.22303 }, // Las Heras
  "50056": { lat: -32.6387, lng: -67.62845 }, // Lavalle
  "50063": { lat: -33.06675, lng: -69.8168 }, // Luján de Cuyo
  "50070": { lat: -32.92182, lng: -68.58154 }, // Maipú
  "50077": { lat: -36.18191, lng: -69.20014 }, // Malargüe
  "50084": { lat: -33.31854, lng: -68.50541 }, // Rivadavia
  "50091": { lat: -34.24172, lng: -69.38363 }, // San Carlos
  "50098": { lat: -32.88161, lng: -68.27361 }, // San Martín
  "50105": { lat: -34.86124, lng: -68.35552 }, // San Rafael
  "50112": { lat: -33.29391, lng: -67.98238 }, // Santa Rosa
  "50119": { lat: -33.62414, lng: -69.54455 }, // Tunuyán
  "50126": { lat: -33.22567, lng: -69.44967 }, // Tupungato
  "54007": { lat: -27.86495, lng: -55.71139 }, // Apóstoles
  "54014": { lat: -27.13572, lng: -54.82099 }, // Cainguás
  "54021": { lat: -27.45856, lng: -55.61641 }, // Candelaria
  "54028": { lat: -27.45317, lng: -55.92973 }, // Capital
  "54035": { lat: -27.89083, lng: -55.45724 }, // Concepción
  "54042": { lat: -26.31883, lng: -54.43348 }, // Eldorado
  "54049": { lat: -26.00256, lng: -54.00841 }, // General Manuel Belgrano
  "54056": { lat: -27.02747, lng: -54.26218 }, // Guaraní
  "54063": { lat: -25.91141, lng: -54.39013 }, // Iguazú
  "54070": { lat: -27.62702, lng: -55.3791 }, // Leandro N. Alem
  "54077": { lat: -26.86029, lng: -54.85321 }, // Libertador General San Martín
  "54084": { lat: -26.67543, lng: -54.60651 }, // Montecarlo
  "54091": { lat: -27.43784, lng: -55.08969 }, // Oberá
  "54098": { lat: -27.16239, lng: -55.29829 }, // San Ignacio
  "54105": { lat: -27.81996, lng: -55.26437 }, // San Javier
  "54112": { lat: -26.52133, lng: -53.98638 }, // San Pedro
  "54119": { lat: -27.37729, lng: -54.68689 }, // 25 de Mayo
  "58007": { lat: -39.1174, lng: -71.0673 }, // Aluminé
  "58014": { lat: -38.12755, lng: -69.22818 }, // Añelo
  "58021": { lat: -39.40625, lng: -70.45491 }, // Catán Lil
  "58028": { lat: -40.09754, lng: -70.34902 }, // Collón Curá
  "58035": { lat: -38.8732, lng: -68.86445 }, // Confluencia
  "58042": { lat: -36.94225, lng: -70.27431 }, // Chos Malal
  "58049": { lat: -39.79295, lng: -71.22825 }, // Huiliches
  "58056": { lat: -40.33838, lng: -71.08442 }, // Lácar
  "58063": { lat: -38.03697, lng: -70.13524 }, // Loncopué
  "58070": { lat: -40.75902, lng: -71.60243 }, // Los Lagos
  "58077": { lat: -36.99166, lng: -70.79589 }, // Minas
  "58084": { lat: -37.65257, lng: -70.73785 }, // Ñorquín
  "58091": { lat: -37.40236, lng: -69.75354 }, // Pehuenches
  "58098": { lat: -39.49077, lng: -69.52448 }, // Picún Leufú
  "58105": { lat: -38.6216, lng: -70.43707 }, // Picunches
  "58112": { lat: -38.92724, lng: -69.81716 }, // Zapala
  "62007": { lat: -40.77012, lng: -63.74107 }, // Adolfo Alsina
  "62014": { lat: -39.35071, lng: -65.99664 }, // Avellaneda
  "62021": { lat: -41.34482, lng: -71.53147 }, // Bariloche
  "62028": { lat: -40.14777, lng: -64.90438 }, // Conesa
  "62035": { lat: -39.50463, lng: -68.27608 }, // El Cuy
  "62042": { lat: -38.66361, lng: -67.61633 }, // General Roca
  "62049": { lat: -41.23669, lng: -67.45721 }, // 9 de Julio
  "62056": { lat: -41.7067, lng: -70.4265 }, // Ñorquinco
  "62063": { lat: -39.35255, lng: -64.72615 }, // Pichi Mahuida
  "62070": { lat: -40.99975, lng: -70.59697 }, // Pilcaniyeu
  "62077": { lat: -41.58213, lng: -65.3908 }, // San Antonio
  "62084": { lat: -41.43906, lng: -66.30699 }, // Valcheta
  "62091": { lat: -41.2172, lng: -68.88474 }, // 25 de Mayo
  "66007": { lat: -24.74282, lng: -63.77231 }, // Anta
  "66014": { lat: -25.10133, lng: -66.05807 }, // Cachi
  "66021": { lat: -26.16679, lng: -65.84335 }, // Cafayate
  "66028": { lat: -24.8482, lng: -65.21252 }, // Capital
  "66035": { lat: -24.97208, lng: -65.42572 }, // Cerrillos
  "66042": { lat: -25.16394, lng: -65.67939 }, // Chicoana
  "66049": { lat: -24.72373, lng: -64.91514 }, // General Güemes
  "66056": { lat: -22.77936, lng: -63.7176 }, // General José de San Martín
  "66063": { lat: -25.74065, lng: -65.46875 }, // Guachipas
  "66070": { lat: -22.80657, lng: -65.01253 }, // Iruya
  "66077": { lat: -24.58508, lng: -65.42598 }, // La Caldera
  "66084": { lat: -26.13219, lng: -64.99737 }, // La Candelaria
  "66091": { lat: -23.75652, lng: -66.18797 }, // La Poma
  "66098": { lat: -25.41065, lng: -65.63055 }, // La Viña
  "66105": { lat: -24.62291, lng: -67.13907 }, // Los Andes
  "66112": { lat: -25.46284, lng: -64.97216 }, // Metán
  "66119": { lat: -25.35379, lng: -66.3612 }, // Molinos
  "66126": { lat: -23.72038, lng: -63.81374 }, // Orán
  "66133": { lat: -23.79935, lng: -62.81979 }, // Rivadavia
  "66140": { lat: -25.90072, lng: -64.6497 }, // Rosario de la Frontera
  "66147": { lat: -24.38523, lng: -65.91216 }, // Rosario de Lerma
  "66154": { lat: -25.70837, lng: -66.09298 }, // San Carlos
  "66161": { lat: -22.32612, lng: -65.01289 }, // Santa Victoria
  "70007": { lat: -31.23978, lng: -68.4353 }, // Albardón
  "70014": { lat: -31.14716, lng: -68.11914 }, // Angaco
  "70021": { lat: -31.46293, lng: -69.83017 }, // Calingasta
  "70028": { lat: -31.53307, lng: -68.53433 }, // Capital
  "70035": { lat: -31.50629, lng: -67.64865 }, // Caucete
  "70042": { lat: -31.48746, lng: -68.52388 }, // Chimbas
  "70049": { lat: -29.47781, lng: -69.48665 }, // Iglesia
  "70056": { lat: -30.48079, lng: -68.34946 }, // Jáchal
  "70063": { lat: -31.62949, lng: -68.38601 }, // 9 de Julio
  "70070": { lat: -31.79325, lng: -68.57972 }, // Pocito
  "70077": { lat: -31.68659, lng: -68.46761 }, // Rawson
  "70084": { lat: -31.55145, lng: -68.64725 }, // Rivadavia
  "70091": { lat: -31.53369, lng: -68.12736 }, // San Martín
  "70098": { lat: -31.53248, lng: -68.45482 }, // Santa Lucía
  "70105": { lat: -32.1185, lng: -68.69803 }, // Sarmiento
  "70112": { lat: -31.24573, lng: -68.79913 }, // Ullum
  "70119": { lat: -30.979, lng: -67.29393 }, // Valle Fértil
  "70126": { lat: -32.0115, lng: -67.75025 }, // 25 de Mayo
  "70133": { lat: -31.71302, lng: -68.91772 }, // Zonda
  "74007": { lat: -32.11612, lng: -67.087 }, // Ayacucho
  "74014": { lat: -32.75084, lng: -66.66037 }, // Belgrano
  "74021": { lat: -33.12955, lng: -65.86485 }, // Coronel Pringles
  "74028": { lat: -32.72304, lng: -65.15277 }, // Chacabuco
  "74035": { lat: -33.92675, lng: -65.56704 }, // General Pedernera
  "74042": { lat: -35.36359, lng: -65.74047 }, // Gobernador Dupuy
  "74049": { lat: -32.11153, lng: -65.52025 }, // Junín
  "74056": { lat: -34.38451, lng: -66.38624 }, // Juan Martín de Pueyrredón
  "74063": { lat: -32.58506, lng: -65.68501 }, // Libertador General San Martín
  "78007": { lat: -50.02745, lng: -69.88345 }, // Corpen Aike
  "78014": { lat: -47.19545, lng: -68.4884 }, // Deseado
  "78021": { lat: -51.35226, lng: -71.55789 }, // Güer Aike
  "78028": { lat: -49.7227, lng: -72.26317 }, // Lago Argentino
  "78035": { lat: -46.71245, lng: -70.39772 }, // Lago Buenos Aires
  "78042": { lat: -48.91701, lng: -68.43237 }, // Magallanes
  "78049": { lat: -48.27086, lng: -71.13313 }, // Río Chico
  "82007": { lat: -32.55181, lng: -61.68909 }, // Belgrano
  "82014": { lat: -33.19744, lng: -61.43703 }, // Caseros
  "82021": { lat: -31.30275, lng: -61.67475 }, // Castellanos
  "82028": { lat: -33.60289, lng: -61.09308 }, // Constitución
  "82035": { lat: -30.90652, lng: -60.04025 }, // Garay
  "82042": { lat: -33.94408, lng: -61.98618 }, // General López
  "82049": { lat: -28.3434, lng: -59.44551 }, // General Obligado
  "82056": { lat: -32.65072, lng: -61.25919 }, // Iriondo
  "82063": { lat: -31.32232, lng: -60.64528 }, // La Capital
  "82070": { lat: -31.53783, lng: -61.12653 }, // Las Colonias
  "82077": { lat: -28.46579, lng: -61.33384 }, // 9 de Julio
  "82084": { lat: -33.12915, lng: -60.71668 }, // Rosario
  "82091": { lat: -30.27337, lng: -61.59577 }, // San Cristóbal
  "82098": { lat: -30.41515, lng: -59.95537 }, // San Javier
  "82105": { lat: -32.15384, lng: -61.03856 }, // San Jerónimo
  "82112": { lat: -30.21298, lng: -60.42536 }, // San Justo
  "82119": { lat: -32.83388, lng: -60.9716 }, // San Lorenzo
  "82126": { lat: -32.00673, lng: -61.86523 }, // San Martín
  "82133": { lat: -28.54023, lng: -60.37422 }, // Vera
  "86007": { lat: -29.05565, lng: -62.82246 }, // Aguirre
  "86014": { lat: -26.53101, lng: -62.70134 }, // Alberdi
  "86021": { lat: -28.69023, lng: -63.85724 }, // Atamisqui
  "86028": { lat: -28.59411, lng: -63.05581 }, // Avellaneda
  "86035": { lat: -27.43189, lng: -64.23669 }, // Banda
  "86042": { lat: -29.1012, lng: -62.13981 }, // Belgrano
  "86049": { lat: -27.89553, lng: -64.37605 }, // Capital
  "86056": { lat: -25.9418, lng: -62.4549 }, // Copo
  "86063": { lat: -28.54002, lng: -64.84729 }, // Choya
  "86070": { lat: -27.393, lng: -63.60666 }, // Figueroa
  "86077": { lat: -28.5915, lng: -62.4419 }, // General Taboada
  "86084": { lat: -27.96025, lng: -64.862 }, // Guasayán
  "86091": { lat: -26.90995, lng: -64.36685 }, // Jiménez
  "86098": { lat: -28.05437, lng: -62.10198 }, // Juan Felipe Ibarra
  "86105": { lat: -28.53393, lng: -64.35467 }, // Loreto
  "86112": { lat: -29.75767, lng: -62.62216 }, // Mitre
  "86119": { lat: -27.29164, lng: -62.2984 }, // Moreno
  "86126": { lat: -29.24152, lng: -64.07492 }, // Ojo de Agua
  "86133": { lat: -26.26601, lng: -64.1191 }, // Pellegrini
  "86140": { lat: -29.30895, lng: -63.46061 }, // Quebrachos
  "86147": { lat: -27.47712, lng: -64.7891 }, // Río Hondo
  "86154": { lat: -30.11899, lng: -62.29528 }, // Rivadavia
  "86161": { lat: -27.85789, lng: -63.79154 }, // Robles
  "86168": { lat: -28.93344, lng: -63.27376 }, // Salavina
  "86175": { lat: -28.19474, lng: -63.83477 }, // San Martín
  "86182": { lat: -28.04606, lng: -63.52515 }, // Sarmiento
  "86189": { lat: -28.21271, lng: -64.30369 }, // Silípica
  "90007": { lat: -26.52653, lng: -64.81042 }, // Burruyacú
  "90014": { lat: -26.89996, lng: -65.07296 }, // Cruz Alta
  "90021": { lat: -27.22682, lng: -65.9187 }, // Chicligasta
  "90028": { lat: -27.03457, lng: -65.41587 }, // Famaillá
  "90035": { lat: -27.7288, lng: -65.23834 }, // Graneros
  "90042": { lat: -27.60374, lng: -65.83536 }, // Juan Bautista Alberdi
  "90049": { lat: -27.82012, lng: -65.58671 }, // La Cocha
  "90056": { lat: -27.20347, lng: -65.08162 }, // Leales
  "90063": { lat: -26.89553, lng: -65.36325 }, // Lules
  "90070": { lat: -27.09339, lng: -65.62452 }, // Monteros
  "90077": { lat: -27.44258, lng: -65.79402 }, // Río Chico
  "90084": { lat: -26.83313, lng: -65.21715 }, // Capital
  "90091": { lat: -27.40026, lng: -65.33254 }, // Simoca
  "90098": { lat: -26.47026, lng: -65.92631 }, // Tafí del Valle
  "90105": { lat: -26.64393, lng: -65.56462 }, // Tafí Viejo
  "90112": { lat: -26.31061, lng: -65.4992 }, // Trancas
  "90119": { lat: -26.78308, lng: -65.31788 }, // Yerba Buena
  "94008": { lat: -53.83002, lng: -68.24942 }, // Río Grande
  "94011": { lat: -54.44639, lng: -67.20588 }, // Tolhuin
  "94015": { lat: -54.82494, lng: -66.50455 }, // Ushuaia
  "94021": { lat: -51.64702, lng: -58.76114 }, // Islas del Atlántico Sur
};
