// Doc-drift fence for every NUMBER the architecture docs state about this repo.
//
// A number in prose is a claim with no owner. AGENTS.md said "48 event types"
// while `EVENT_TYPES` held 55, and the git history shows that same line stale at
// 23, 39, 45 and 47 before that. Nothing failed, because nothing was checking.
//
// The instrument is `docs/architecture/facts.json`, generated by
// `pnpm facts:write` (`scripts/architecture-facts.ts`). Docs cite a number as
//
//     <!-- fact:event_types -->55<!-- /fact -->
//
// and this file holds three things together:
//
//   (a) facts.json vs THE TREE — the generator is re-run in-process and must
//       reproduce the committed file exactly. Exact equality, no floors and no
//       tolerances: a floor here would mean "the number may drift upward in
//       silence", which is the failure being fenced.
//   (b) the markers vs facts.json — every `fact:` marker in the scanned docs
//       must carry the generated value, and an unknown key fails rather than
//       being ignored. A marker nobody generates is a number nobody owns.
//   (c) backticked repo paths in `docs/architecture/**` must exist on disk.
//       A doc that cites a file deleted two refactors ago reads as evidence and
//       is not. (`dim-interno:docs/presentation/` used to be a second root; it moved to the
//       private companion repo dim-interno on 2026-09-18 and is no longer
//       scanned from here.) Tolerating a missing directory is how a scope
//       becomes a silent no-op, so the roots are asserted rather than assumed:
//       `DOC_TREE_ROOTS` + `ROOT_DOCS` are reported present or absent by name,
//       and every entry of `REQUIRED_ROOTS` (`docs/architecture`, `AGENTS.md`,
//       `CLAUDE.md`) must exist. Renaming a real root cannot
//       quietly empty this fence, and the marker count is checked PER root so
//       markers in one cannot cover for a scan that stopped reading another.
//
// DB-less: the generator imports only pure constant modules and reads the
// filesystem, so this runs in the `unit` project with no database.

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { FACTS_JSON, type FactsFile, REPO_ROOT, computeFacts } from "@/scripts/architecture-facts";

const committed = JSON.parse(readFileSync(join(REPO_ROOT, FACTS_JSON), "utf8")) as FactsFile;

// ---------------------------------------------------------------------------
// Doc discovery
// ---------------------------------------------------------------------------

/** Every `.md` under `rel`, recursively. Tolerates a missing directory. */
function markdownUnder(rel: string): string[] {
  const abs = join(REPO_ROOT, rel);
  if (!existsSync(abs)) return [];
  const acc: string[] = [];
  const walk = (dir: string, prefix: string): void => {
    for (const ent of readdirSync(dir, { withFileTypes: true })) {
      if (ent.isDirectory()) walk(join(dir, ent.name), `${prefix}/${ent.name}`);
      else if (ent.name.endsWith(".md")) acc.push(`${prefix}/${ent.name}`);
    }
  };
  walk(abs, rel);
  return acc.sort();
}

/** The doc trees this fence owns end to end. */
const DOC_TREE_ROOTS = ["docs/architecture"];
/** Root docs that also carry markers, but whose paths are NOT asserted yet. */
const ROOT_DOCS = ["AGENTS.md", "CLAUDE.md"];

/** Roots that MUST exist, so no rename can empty the marker scan in silence. */
const REQUIRED_ROOTS = ["docs/architecture", ...ROOT_DOCS];

const DOC_TREES = DOC_TREE_ROOTS.flatMap((root) => markdownUnder(root));

const read = (rel: string): string => readFileSync(join(REPO_ROOT, rel), "utf8");

// ---------------------------------------------------------------------------
// Path extraction
// ---------------------------------------------------------------------------

const REPO_PREFIX =
  /^(app|lib|src|db|scripts|packages|apps|components|__tests__|\.github|docs|e2e)\//;
// A backticked span that is not a concrete path: a glob, a `<placeholder>`, a
// brace set, a prose arrow, or a `file::symbol` reference.
const NOT_A_PATH = /[*<>{}\s]|→|::/;

/** The repo path a backticked span names, or null if it does not name one. */
function pathIn(span: string): string | null {
  const raw = span.trim();
  if (!REPO_PREFIX.test(raw) || NOT_A_PATH.test(raw)) return null;
  // Strip a trailing `#anchor` and a trailing `:12`, `:12-30` or `:1,5-9`.
  const p = raw.replace(/#[^#]*$/, "").replace(/:[\d,\s-]+$/, "");
  return !p || p.endsWith("/") ? null : p;
}

/** Backticked repo paths in `rel`, as [path, span] pairs. */
function citedPaths(rel: string): { path: string; span: string }[] {
  const out: { path: string; span: string }[] = [];
  for (const m of read(rel).matchAll(/`([^`\n]+)`/g)) {
    const path = pathIn(m[1]);
    if (path) out.push({ path, span: m[1].trim() });
  }
  return out;
}

/**
 * Paths the docs cite ON PURPOSE that no longer exist.
 *
 * `hexagonal-lite.md` narrates a migration AWAY from these files and says so in
 * as many words (":153 — the `app/actions/events.ts` path no longer exists").
 * Asserting they exist would be asserting the migration never happened. Each is
 * listed individually rather than exempting the file, so a NEW dangling path in
 * the same document still fails.
 */
const HISTORICAL_PATHS = new Set([
  // hexagonal-lite.md — pre-refactor homes, and the `lib/` re-export shims that
  // were removed once every importer was repointed.
  "app/actions/events.ts",
  "lib/case-helpers.ts",
  "lib/capabilities.ts",
  "lib/govt-home-kpis.ts",
  "lib/govt-dashboards.ts",
  // retention-policy-pending-decision.md — names the purge module by its ARCH-G
  // path; the code moved when the module was split.
  "lib/data-lifecycle.ts",
]);

// ---------------------------------------------------------------------------

describe("architecture facts — the file matches the tree", () => {
  it("(a) recomputing the generator reproduces facts.json exactly", () => {
    expect(
      computeFacts(REPO_ROOT),
      "docs/architecture/facts.json is stale — run `pnpm facts:write` and commit the result",
    ).toEqual(committed.facts);
  });

  it("every fact carries a source and a method", () => {
    const thin = Object.entries(committed.facts)
      .filter(([, f]) => !f.source?.trim() || !f.method?.trim() || typeof f.value !== "number")
      .map(([k]) => k);
    expect(thin, "facts missing a value, a source or a method").toEqual([]);
  });
});

describe("architecture facts — the docs cite them by marker", () => {
  const MARKER = /<!-- fact:([\w]+) -->(.*?)<!-- \/fact -->/g;
  const scanned = [...DOC_TREES, ...ROOT_DOCS];

  const markers = scanned.flatMap((rel) =>
    [...read(rel).matchAll(MARKER)].map((m) => ({ rel, key: m[1], text: m[2] })),
  );

  it("the declared roots are real, and the absent one is named", () => {
    // `markdownUnder` returns [] for a missing directory, so a scope declared
    // here and absent from the tree is a no-op that reads like coverage. State
    // which roots exist, and require the ones that carry markers today.
    const present = [...DOC_TREE_ROOTS, ...ROOT_DOCS].filter((r) => existsSync(join(REPO_ROOT, r)));
    const absent = [...DOC_TREE_ROOTS, ...ROOT_DOCS].filter((r) => !present.includes(r));
    console.log(
      `[architecture-facts] roots present: ${present.join(", ") || "none"}` +
        ` — absent (scanned when they land): ${absent.join(", ") || "none"}`,
    );
    const missing = REQUIRED_ROOTS.filter((r) => !present.includes(r));
    expect(
      missing,
      "roots this fence depends on are gone — a rename would empty the marker scan without failing it",
    ).toEqual([]);
  });

  it("the marker scan is not vacuous, per root", () => {
    // Without this, a broken regex turns the next two tests into no-ops that
    // pass forever. R3 of the canon's own rulebook: an enforcer that cannot
    // fail is no enforcer. Counting globally is not enough: markers in
    // `docs/architecture` alone would mask a scan that stopped reading
    // `AGENTS.md`, which is the file the stale "48 event types" line lived in.
    const under = (root: string): number =>
      markers.filter((m) => m.rel === root || m.rel.startsWith(`${root}/`)).length;
    for (const root of ["docs/architecture", "AGENTS.md"]) {
      expect(
        under(root),
        `no \`fact:\` markers found under ${root} — the scan or the docs broke`,
      ).toBeGreaterThan(0);
    }
    expect(
      markers.length,
      "no `fact:` markers found at all — the scan or the docs broke",
    ).toBeGreaterThan(0);
  });

  it("(b) every marker names a generated fact", () => {
    const unknown = markers
      .filter((m) => !(m.key in committed.facts))
      .map((m) => `${m.rel}: fact:${m.key}`);
    expect(
      unknown,
      "markers naming a key that facts.json does not generate — add it to `scripts/architecture-facts.ts` or drop the marker",
    ).toEqual([]);
  });

  it("(b) every marker states the generated value", () => {
    const wrong = markers
      .filter((m) => m.key in committed.facts && m.text !== String(committed.facts[m.key].value))
      .map(
        (m) =>
          `${m.rel}: fact:${m.key} says "${m.text}", facts.json says "${committed.facts[m.key].value}"`,
      );
    expect(wrong, "doc markers disagree with facts.json").toEqual([]);
  });
});

describe("architecture facts — the docs cite paths that exist", () => {
  const cited = DOC_TREES.flatMap((rel) => citedPaths(rel).map((c) => ({ ...c, rel })));

  it("the path scan is not vacuous", () => {
    expect(
      cited.length,
      "no backticked repo paths found in the doc trees — the scan broke",
    ).toBeGreaterThan(0);
  });

  it("(c) every backticked repo path under docs/architecture exists", () => {
    const dangling = cited
      .filter((c) => !HISTORICAL_PATHS.has(c.path) && !existsSync(join(REPO_ROOT, c.path)))
      .map((c) => `${c.rel}: \`${c.span}\``);
    expect(dangling, "docs cite repo paths that do not exist").toEqual([]);
  });

  it("(c) the historical-path allowlist has no dead entries", () => {
    // An allowlist that outlives its reason is a hole. If one of these files
    // comes back, it stops being an exception and must leave the list.
    const resurrected = [...HISTORICAL_PATHS].filter((p) => existsSync(join(REPO_ROOT, p)));
    expect(
      resurrected,
      "allowlisted paths that exist again — remove them from HISTORICAL_PATHS",
    ).toEqual([]);
  });

  it("reports, without asserting, the dangling paths in AGENTS.md and CLAUDE.md", () => {
    // Deliberately NOT an assertion. These two files are the project's oldest
    // prose and carry references a later doc-fix lane will handle; pinning them
    // here would either fail on day one or freeze a number nobody chose. The
    // scan still has to WORK, which is what the non-vacuity check below buys.
    const rootCited = ROOT_DOCS.flatMap((rel) => citedPaths(rel).map((c) => ({ ...c, rel })));
    const dangling = rootCited.filter((c) => !existsSync(join(REPO_ROOT, c.path)));
    console.log(
      `[architecture-facts] AGENTS.md + CLAUDE.md: ${rootCited.length} backticked repo paths, ` +
        `${new Set(dangling.map((d) => d.path)).size} distinct dangling — ` +
        `${[...new Set(dangling.map((d) => d.path))].join(", ") || "none"}`,
    );
    expect(rootCited.length, "the root-doc path scan found nothing — it broke").toBeGreaterThan(0);
  });
});
